#!/bin/sh

# Set up X11 for multiple monitors.
# Probably not needed, unless your system
# finds the monitors in the "wrong" order.

set -x

# Simple version, from phessler@
xrandr --output VGA-0 --right-of LVDS
xrandr --output VGA-0 --auto
xrandr --output LVDS --auto

