#!/bin/sh

# for now just checks images

awk '
/^image::/ {
	n=split($0, stuffs, /::/)
	l = length(stuffs[2])
	file = substr(stuffs[2], 1, l - 2)
	# print $0 " -> " n " file=" file
	if (system("[ -f " file " ]")) {
		print("Missing image file " file)
	}
} ' $*
