#!/bin/sh

INDEX=/usr/ports/INDEX

if [ ! -r ${INDEX} ]; then
	echo "$0: cannot read index file ${INDEX}" >&2
	exit 1
fi

for arg
do
	egrep $arg ${INDEX}
done |
	awk -F'|' '{printf "Name: %s (%s)\nDesc: %s\n\n",$1,$2,$4}'
