#!/bin/sh

PROG=$1

N=$(which ${PROG} 2>/dev/null | wc -l)
case ${N} in
	*" "0" ") echo Not in PATH: ${PROG} >&2 ;;
	*" "1" ") ln -s $(which ${PROG}) ${AUTOSTART_DIR} ;;
	*) echo ${PROG} ambiguous;;
esac
