#!/bin/sh

# Load the BBClientLib and the ClientMain onto the connected BB device
# Set up for "GIT Bash" configuration of *Nix under WindBLows.

RIM_JAVA_BIN="/c/Eclipse/plugins/net.rim.ejde.componentpack7.0.0_7.0.0.33/components/bin"

cd ~/git/Razorback/Clients/BBClientMain/deliverables/Standard/7.0.0

${RIM_JAVA_BIN}/JavaLoader.exe load org.ehealthinnovation.mrpm.bbclientlib.cod \
	org.ehealthinnovation.mrpm.clientmain.cod

