#!/bin/sh

# take key config files from a machine (NOT including any passwd files!!)

[ -w / ] || { echo be root
	exit 1
}
FILE=$HOME/config.tar.gz

cd /
tar czvf ${FILE} \
	etc/defaultdomain \
	etc/exports \
	etc/hosts etc/hostname.* \
	etc/inetd.conf \
	etc/master.passwd etc/passwd \
	etc/mail/ \
	etc/mygate \
	etc/myname \
	etc/networks \
	etc/newsyslog.conf \
	etc/pf.conf \
	etc/rc.local \
	etc/rc.conf.local \
	etc/rc.securelevel \
	etc/resolv.conf* \
	etc/services \
	etc/shells \
	etc/ssh/ \
	etc/sysctl.conf \
	etc/syslog.conf \
	etc/ttys \
	upgrade.site

echo "Remember to copy ${FILE} from this system, and keep it secure."
