#!/bin/ksh 

# Back up the membership and options in the mailing lists

#scp -r root@darwinsys.com:/var/spool/mailman/lists ~/bkup
ssh root@darwinsys.com:/var/spool/mailman/{qfiles,spam,archives,cgi-bin,data,icons,locks,mail,scripts,templates} ~/bkup
scp -r root@darwinsys.com:/var/spool/mailman/{qfiles,spam,archives,cgi-bin,data,icons,locks,mail,scripts,templates} ~/bkup

