#!/bin/sh

# add an IP to spamd blacklist file, and tell pf to add it to kernel

[ -w / ] || {
	echo be walking roots
	exit 1
}

FILE=/etc/mail/myblack.txt # mentioned in /etc/spamd.conf
TABLE=spamd

for h
do
	grep $h ${FILE}
	case $? in
	2)
		echo Not added!
		;;
	0)
		echo "$h: Already listed!"
		;;
	1)
		echo "$h # added  by ian using $0 `date`" >> ${FILE}

		pfctl -t ${TABLE} -T add $h
		;;

	esac

done
