#!/bin/sh

# add an entry to the block list

case $# in
	1|2)	;;
	*)	echo usage: "+|-" host;;
esac

[ -w / ] || {
	echo "Be walking root, be talking flowers">&2; exit 1 
}
host=${2-daroo}

case $1 in
	'-')
		pfctl -t blockedinside -T delete ${host}
		;;
	'+')
		pfctl -t blockedinside -T add ${host}
		;;
esac
