#!/bin/sh

# V0: bloggit 'my title' '[my subtitle]' <<! body on stdin
# singlequotes to be escaped
# !

# V1: getopts, so:
#	-f file
#	-q 		# no quote doubling
#	-s subtitle

PROGNAME=$0
TITLE=$1
SUBTITLE=$2
ID=$(date +%Y/%m/%d/%H/%M000000000)
BODY=$(sed -e "s/'/''/g")

ssh dos psql -d website <<!
insert into blog(id, title, subtitle, body) values('$ID','$TITLE','$SUBTITLE', '$BODY');
!
