#!/bin/sh

TOPICS=${HOME}/workspace/bookmarks/topics.txt

# insert a bookmark, given topic, url, and text
function check_topic {
	rg -q "^$1 " ${TOPICS} || {
		echo "Topic $1 not found"
		exit 1
	}
}

case $# in
3)
	check_topic $1
	echo "insert into bookmark(owner,topic, url, text) values(1, '$1', '$2', '$3');" |
		psql -d bookmarks
	;;
1)
	if [ $1 == '-t' ]; then
		cat ${TOPICS}
		exit 0
	fi
	check_topic $1
	echo "select text, url from bookmark where topic = '$1' order by text" | psql -d bookmarks
	;;
*) 
	echo "Usage: $0 topic url text" >&2
	exit 1
	;;
esac


