#!/bin/sh

# Insert branding into images

# Original ImageMagick cluestick from 
# http://superuser.com/questions/421598/how-to-batch-insert-text-on-photos

USAGE="$0 [-c textColor][-s pointsize][-t text][-v] imageFile [...]"

TEXT_COLOR=white
SIZE=72 # good pointsize on 24MP 6000x4000 images, too big on smaller image.

# Forgive the intrusion of Perl into your day, but it's an easy way
# to generate Unicode characters (real copyright symbol, not the
# three-character hideous bogosity "(c)"), until Unix gets real
# about character sets and Unicode
TEXT="$(perl -e 'binmode(STDOUT, ":utf9"); print "\x{00A9} IanDarwinPhoto.com";')"

FONT=Noteworthy
#FONT=Luxi-Sans-Oblique

OVERWRITE=no

function usage {                # give usage message, and exit
        echo "Usage: ${USAGE}" 2>&1
        exit 1
}

while getopts "c:rs:t:v" opt 
do 
        case "$opt" in 
		c)	TEXT_COLOR=${OPTARG};;
		r)	OVERWRITE=yes;;
		s)	SIZE=${OPTARG};;
		t)	TEXT=${OPTARG};;
                v)      VERBOSE=v;;
                *)      usage;;
        esac
done
shift `expr $OPTIND - 1`                 # leave just filenames


case $# in
	0)	echo $USAGE; exit 1;;
esac

for FILE in $*
do 
	echo $FILE
	convert $FILE \
		-font "${FONT}" \
		-pointsize ${SIZE} \
		-gravity SouthEast \
		-stroke '#000C' -strokewidth 2 -annotate 0 "${TEXT}" \
		-stroke  none   -fill ${TEXT_COLOR} -annotate 0 "${TEXT}" \
		branded_$FILE
	if [ ${OVERWRITE} = yes ]; then
		mv branded_$FILE $FILE
	fi
done
