#!/bin/sh

# Insert branding into images

# Original ImageMagick cluestick from 
# http://superuser.com/questions/421598/how-to-batch-insert-text-on-photos

USAGE="$0 imageFile [...]"

# Forgive the intrusion of Perl into your day, but it's an easy way
# to generate Unicode characters (real copyright symbol, not the
# three-character hideous bogosity "(c)"), until Unix gets real
# about character sets and Unicode

TEXT="$(perl -e 'binmode(STDOUT, ":utf9"); print "\x{00A9} IanDarwinPhoto.com";')"

case $# in
	0)	echo $USAGE; exit 1;;
esac

for FILE in $*
do 
	echo $FILE
	convert $FILE \
		-font Luxi-Sans-Oblique \
		-pointsize 72 \
		-gravity SouthEast \
		-stroke '#000C' -strokewidth 2 -annotate 0 "${TEXT}" \
		-stroke  none   -fill white    -annotate 0 "${TEXT}" \
		branded_$FILE
done
