#!/bin/sh

# Set the font variable. It's not used yet.

BIGFONT='-*-lucidatypewriter-bold-*-*-*-24-*-*-*-*-*-*-*'
# if [ -x /usr/local/bin/konsole ]; then
# 	konsole -font ${BIGFONT}
# else
 	xterm -bg white -fg black -fn ${BIGFONT}
# fi
