#!/bin/sh

# burn a dvd from an existing "iso" 9660 DVD image

# $ whichpkg growisofs
# dvd+rw-tools-5.21.4.10.8p0:bin/growisofs

case $# in
	#0) IMAGE=dvd.iso;;
	1) IMAGE=$1;;
	*) Usage: $0 dvd-iso-file;;
esac

growisofs -Z /dev/rcd0c=$1

disklabel /dev/rcd0c
