#!/bin/sh

# burn a CD

if [ ! -w / ]; then
	echo be root
	exit 1
fi

USAGE="$0 [-f device][-v] image.iso"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

DEVICE=cd0
DUMMY=""
SPEED=48

while getopts "df:s:v" opt 
do 
 	 case "$opt" in 
		d)	DUMMY=-dummy;;
		f)	DEVICE=$OPTARG;;
		s)	SPEED=$OPTARG;;
		v)	VERBOSE=v;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

set -e

        

IMAGE=$1

ISOSIZE=-isosize
ISOSIZE=""

UNAME=`uname`
case "$UNAME" in
OpenBSD)
	if [ ! -x /usr/local/bin/cdrecord ]; then
		echo "Error: cdrecord not found" >&2
		exit 1
	fi
	echo -n "Is there a blank CD in drive $DEVICE, and NO CD PLAYER SW RUNNING? Then press enter"
	read junk

	set -x
	#OVERBURN="-overburn"
	#BURNFREE="-driveropts=burnfree"
	MODE=-sao
	#MODE=-raw96r
	cdrecord ${MODE} ${OVERBURN} -v $DUMMY speed=${SPEED} dev=/dev/${DEVICE}c $ISOSIZE ${IMAGE-./*.fs}

	mount -t cd9660 /dev/${DEVICE}c /mnt

	ls . /mnt

	umount /dev/${DEVICE}c

	eject  /dev/${DEVICE}c
	;;

Darwin)
	echo "Burning using hdiutil for Mac OS X" >&2
	hdiutil burn -noeject $IMAGE 

	# OS X will automount it with -noeject:
	ls /Volumes
	;;

*)
	echo "Error: need to update this script for ${UNAME}" >&2
	;;

esac
