#!/bin/sh

# Check a bunch of hosts at once.

host -t any darwinsys.com
for f in \
	mail.darwinsys.com \
	androidcookbook.com \
	javacook.darwinsys.com \
	tomcatbook.darwinsys.com 
do
	echo ";----- $f -----"
	host $f
	ping -c1 $f >/dev/null 2>&1
done
