#!/bin/sh

# copy source files used in O'Reilly Atlas "snippets" from code repos into the book repo
# We mostly have to use Snippets instead of full code files due to Java's verbosity :-)

for dir in $ws/javasrc $ws/darwinsys-api

do
	cd ${dir}
	grep -lr //.BEGIN src | cpio -pmud --quiet ~/book/jcb
done
