#!/bin/sh -e

# copy source files used in O'Reilly Atlas "snippets" from code repos into the book repo
# We mostly have to use Snippets instead of full code files due to Java's verbosity :-)

DEST=~/book/jcb
SUBDIR=src # or code, or whatever

for dir in $ws/javasrc $ws/darwinsys-api $ws/java8src $ws/javasrcee
do
	(
	cd ${dir}
	grep -lr '^[ \t]*// BEGIN' ${SUBDIR}
	find ${SUBDIR}/src/main/resources -name \*.json -o -name \*.xml -print
	) | cpio -pmud --quiet ${DEST}
done

cd ${DEST}/${SUBDIR}
grep -lr '\t' . | xargs detab
