#!/bin/ksh

if [ $# -lt 2 -o $# -gt 3 ]; then
	echo "Usage: count start end"
	exit 1
fi

start=$1
end=$2
by=${3-1}
# $start .. $end by $by
i=$start
while [ $i -le $end ]
do
	echo "$i"
	i=$(expr $i + $by)
done
