#!/bin/sh

for WF in "${wf}" /var/wildfly* ~/wildfly*
do
	if [ ! -z "${WF}" -a -d "${WF}" ]; then
		FOUND=true
		break;
	fi
done
if [ -z ${FOUND} ]; then
	echo wildfly flew?
	exit 1
fi

D=$(find ${WF}/standalone/tmp/vfs/temp -name $1)
case ${D} in
	"* *") echo Name not unique! >&2
		exit 2;;
	"")	echo "Not found" >&2
		exit 1;;
esac

set -x 
	
cp $w/$1 ${D}
