#!/bin/ksh

# cptree old new
# old is presumably (but not necessarily) a mount point

# can use tar or cpio; default is:
TYPE=CPIO

PATH=/bin:/usr/bin:$PATH; export PATH

USAGE="$0 [-v] old new"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

function ckdir {		 # scope out this here directory
	case $1 in
		/*)	;;
		*)	echo "$0: Directory $1 must be full path"
			exit 1;;
	esac

	if [ ! -d $1 ]; then
		echo "$0: $1 must be existing directory"
		exit 1
	fi

	# now really cd there to worry about symlinks, perms, etc.
	cd $1 || exit 1
}

while getopts "ctv" opt 
do 
 	 case "$opt" in 
		c)	TYPE=CPIO;;
		t)	TYPE=TAR;;
		v)	VERBOSE=v;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

if [ $# -ne 2 ]; then
	usage
fi

old=$1
new=$2

case $new in
""|".") echo "$0: new location $new must be a full path!"
	exit 1;;
esac
ckdir $new		# validate new first
ckdir $old		# validate old, stay there for tar/cpio

case $TYPE in
	CPIO)
		find . -type f -o -type l -depth -print | cpio -ocB | ( cd $new; cpio -icBmud${VERBOSE})
		;;
	TAR)
		tar cf - . | (cd $new; tar xpf${VERBOSE} -)
		;;
esac
