#!/bin/sh

# One-time copy from a **local** CVS repo to a remote GIT repo
# Intended to be permanent; there is no convenient resync later.
# requires cvs2git package installed.

rm -rf	$HOME/cvs2git-tmp/
mkdir	$HOME/cvs2git-tmp/

LOCAL_CVS=/cvs/macosui
NEW_GIT_NAME=macosui
GIT_USER_NAME=IanDarwin
REMOTE_GIT=git@github.com/IanDarwin/${NEW_GIT_NAME}.git

cd $HOME/git

cvs2git \
	    --blobfile=$HOME/cvs2git-tmp/git-blob.dat \
	    --dumpfile=$HOME/cvs2git-tmp/git-dump.dat \
	    --username=${GIT_USER_NAME} \
	    ${LOCAL_CVS}

rm -rf	${NEW_GIT_NAME} # in case we failed earlier
mkdir	${NEW_GIT_NAME}
cd	${NEW_GIT_NAME}

git init --bare

replace '^committer ian' 'committer idarwin' $HOME/cvs2git-tmp/git-dump.dat

git fast-import --export-marks=$HOME/cvs2git-tmp/git-marks.dat < $HOME/cvs2git-tmp/git-blob.dat
git fast-import --import-marks=$HOME/cvs2git-tmp/git-marks.dat < $HOME/cvs2git-tmp/git-dump.dat

git gc --prune=now

cd /tmp
rm -rf ${NEW_GIT_NAME}
git clone ${HOME}/git/${NEW_GIT_NAME}

cd ${NEW_GIT_NAME}

ls

if [ -f .cvsignore ]; then
	mv .cvsignore .gitignore
	git add $_
	git commit -m "Move .cvsignore to .gitignore"
fi

git remote remove origin
git remote add origin ${REMOTE_GIT}

echo "OK to push?"; read ans junk; case $ans in
y|Y)	;;
*)	exit 1;;
esac

git push -u origin master
