#!/bin/sh

# One-time copy from a **local** CVS repo to a **local** GIT repo

# Defaults
GITHUB_USER=IanDarwin

case $# in
1)	REPO=$1;;
*)	echo "Usage: $0 repoName [same name used in git as in CVS]" >&2
	exit 1;;
esac

CVS_REPO=/cvs/${REPO}
GIT_REPO=/git/${REPO}

if [ ! -d ${GIT_REPO} ]; then
	doas newgitrepo ${REPO} || exit
fi

TMP=$(mktemp /tmp/cvs2gitrepoXXXXXX)

cvs2gitdump -a -e darwinsys.com ${CVS_REPO} > $TMP

git --git-dir ${GIT_REPO} fast-import < $TMP

cd /tmp; rm -rf ${REPO}; git clone ${GIT_REPO}

cd ${REPO}

if [ -f .cvsignore ]; then
	git mv .cvsignore .gitignore
	git commit -m "Rename .cvsignore to .gitignore"
fi

git remote remove origin
git remote add origin ${GIT_REPO}

git push -u origin master

echo "Rename CVS repo to .bak?"; read ans junk; case $ans in
y|Y*)	mv /cvs/${REPO} /cvs/${REPO}.bak;;
esac
