#!/bin/sh

# Debug the JDK. Unmaintained for years.

cd /home/ian/ports-others/devel/jdk/1.8.self/w-jdk-1.8.1/java/build/bsd-powerpc

export JAVALIB=libjava.so
export LD_BIND_NOW=true
export _JVM_THREADS_TYPE=native_threads
export LD_LIBRARY_PATH=./lib/powerpc/native_threads:./lib/powerpc/classic:./lib/powerpc
gdb ./bin/powerpc/native_threads/java 
