#!/bin/sh

# Copy a file to multiple hosts

THISHOST=`hostname`

for file
do
	for host in `cat ~/.netsh_hosts`
	do
		echo $host
		if [ "$host" = $THISHOST ]
		then
			echo "(bypassed)"
		else
			scp $file ${host}:$file
		fi
	done
done
