#!/usr/bin/awk -f

BEGIN {
	DIR="/home/ian/doc/"
	INDEX=DIR "index.txt"
	OPEN_CMD="open" # my script, native on osx; for Windoze use "start"
	print "Index = " INDEX
	numlines = 0
	while (getline line < INDEX) {
		n = split(line, kv);
		#print "READ", kv[1], " --> ", kv[2]
		map[kv[1]] = kv[2]
		++numlines
	}
	#print "Read " numlines " entries"
	for (i = 1; i < ARGC; i++) {
		k = ARGV[i]
		v = map[ARGV[i]]
		print k, "=>", v
		if (v == "") {
			print("NO MATCH FOR", k)
		} else {
			system(OPEN_CMD " " DIR v)
		}
	}
	exit(0)
}
