#!/bin/sh 

# dse - data security erase, named for old IBM mainframe tape erase command

case $# in
1)	;;
*)	echo usage $0 disk
	exit 1
	;;
esac
disk=$1

BS=10m

function devi {
case ${1} in
1) DEV=/dev/zero;;
2) DEV=/dev/urandom;;
3) DEV=/dev/zero;;
4) DEV=/dev/urandom;;
esac
echo $DEV
}

disklabel ${disk}

echo -n "OK to totally erase disk ${disk}"?
read ans

if [ "yes" != ${ans} ];
then	
	echo OK, I wont.
	exit
fi

mount | grep /dev/${disk} && {
	echo "It appears mounted, are you sure?"
	read ansagain
	if [ "yes" != ${ansagain} ];
	then exit
	fi
}

for pass in 1 2 3
do
	echo start pass ${pass} using $(devi $pass) on ${disk} at $(date)
	dd if=$(devi $pass) of=/dev/${disk}c bs=${BS}
done

echo "Done with Disk ${disk}; probably clean, at $(date)"
strings < /dev/${disk}c | head -2
fdisk -i ${disk}
