#!/bin/sh

# Export /usr/ports as a tar file, for scp to machine on LAN
# Exclude the subdirs that you don't want
# (can always scp individual distfiles)

tar cfz /tmp/ports.tgz $(ls | egrep -v distfiles\|packages\|pobj)

echo "Remember to run this after untarring:"
echo "mkdir /usr/ports/{distfiles,packages,pobj}"
