#!/bin/sh

cd $ws || exit

case $(uname) in
Darwin)	DEST=/Volumes/I*;;
*)	DEST=/mnt;;
esac

for dir in $*
do
	rm -r ${dir}/{build,bin,dist}
	zip -r -xCVS /tmp/${dir}.zip ${dir}/ && mv /tmp/${dir}.zip ${DEST}
done
