#!/bin/ksh

PORTSWEBDIR=$ws/darwinsysweb/web/openbsd/myports

function usage {
	echo >&2 "Usage: $0 category port"
	exit 0
}

case $# in
	2);;
	*) usage;
esac

category=$1
port=$2

cd /usr/ports/mystuff

if [ ! -d ${category}/${port} ]; then
	echo "No such port in `pwd`" >&2
	exit 1
fi

(cd ${category}/${port}
	find . -name '.#*' -o -name '*.orig' -o -name '*.rej' | xargs sudo rm -f
	)

PORT_TGZ=${port}.tar.gz

tar czvf ${PORTSWEBDIR}/${PORT_TGZ} ${category}/${port}

cd ${PORTSWEBDIR}
webinst ${PORT_TGZ}
echo port is at http://www.darwinsys.com/openbsd/myports/${PORT_TGZ}
