#!/bin/sh 

# Export javasrc (and jabadot, since it's used several places in Java Cookbook)

set -x

cd /tmp

for dir in javacook javasrc
do
	if [ -d ${dir} ]; then
		mv ${dir} ${dir}-$$
		rm -rf ${dir}-$$ &
	fi
done

cvs -q -d /cvs export -D now javacook-src src/jabadot

mv javasrc javacook

mv src/jabadot javacook/jabadot

# Next section done in the subdirectory
(
	cd javacook

	# Remove any private gunk
	rm com.darwinsys.util/upload

	# Update the index.html for just what we exported
	(cd netweb; jikes +E -d .. MkIndex.java)
	java MkIndex

	# Build simple makefiles where needed.
	make makefiles

)
# No longer in subdirectory

rm -f javacooksrc.zip
fastjar cvf javacooksrc.zip ./javacook

scp javacooksrc.zip darwinsys.com:/www/javacook/ &&
	echo "JavaCook src updated at javacook.darwinsys.com/download.html" |
		Mail -s "java cookbook download updated" -v "Mary Hubben <maryh@oreilly.com>"

# Now extract the whole mess so people can browse individually
ssh darwinsys.com "cd /www/javacook; unzip javacooksrc.zip javacook/*"
