#!/bin/sh 

set -x

cd /tmp

cvs -d /cvs export -D now javacook-src

mv javasrc javacook

# Update the index.html for just what we exported
(cd javacook; java MkIndex)

# this ought to be good for a laugh the first time out!
#jikes +E -d /tmp */*.java

fastjar cvf javacooksrc.zip ./javacook
