#!/bin/sh -f

# Export javasrc for distro with JavaCook web site.

set -x

cd ~/book/jcb

# Next section done in the subdirectory
#(
#	cd javacooksrc
#
#	# Update the index.html for just what we exported
#	(cd netweb; 
#	mkdir /tmp/classes; javac -d /tmp/classes MkIndex.java)
#	java -cp /tmp/classes netwed.MkIndex
#
#)
# No longer in subdirectory

# ensure symlink exists, it is not in git
rm -f javacooksrc
ln -s src javacooksrc

#
rm -f javacooksrc.zip
jar cvf javacooksrc.zip javacooksrc/*

exit 

# Now extract the whole mess so people can browse individually
# Note that this extracts in javacook/javacook, which is a bit confusing.
# ssh darwinsys.com "cd /www/javacook; unzip -fo javacooksrc.zip"
