#!/bin/sh

PORT=9090

USAGE="$0 [-p nnn] [response-file]"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "p:" opt 
do 
 	 case "$opt" in 
		p)	PORT=${OPTARG};;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filename

case $# in
	0) FILENAME=/tmp/qwertymonster;;
	1) FILENAME=$1;;
	*) usage;;
esac

if ! [ -r $FILENAME ]; then
cat> $FILENAME <<!

<html>
<title>Foo!</title>
<h1>Vittory!</h1>
!
fi

while :
do 
	(
	echo "200 HTTP/1.0 OK"
	echo "Date: $(date)"
	echo
	cat $FILENAME
	) |
		nc -l $PORT
done
