#!/bin/sh

PORT=9090

USAGE="$0 [-p nnn]"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "p:" opt 
do 
 	 case "$opt" in 
		p)	PORT=${OPTARG};;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filename

while :
do 
	(
	echo "200 HTTP/1.0 OK"
	echo "Date: $(date)"
	echo ""				# required separator
	if [ -z "${RESPONSE}" ]; then
	echo "<html>
<title>Welcome!</title>
<h1>Welcome</h1>
<p>Welcome at $(date)!</p>
	"
	else echo ${RESPONSE}
	fi
	) |
		nc -l $PORT
done
