#!/bin/sh

# The schizophrenic CUPS printer that is sometimes on my USB port (so I can use it as 
# a scanner, it's really an MFC) and sometimes on a print server (when I'm not around).
# In these two cases it may also be accessed by people on the LAN
case $1 in
	usb|local)
		/usr/local/sbin/lpadmin -h usb:/dev/ulpt0 -p hpmfc
		;;
	ianprint|rem*)
		/usr/local/sbin/lpadmin -h socket://ianprint:9100 -p hpmfc
		;;

	# For use by family
	dalai)
		case $(hostname) in
		dalai*)	echo "Can't network print to yourself!!"
			;;
		*)
			lpadmin -h ipp://dalai/printers/hpmfc -p hpmfc
		esac
		;;
	*)
		echo huh?
		;;
esac
