#!/bin/sh

# ForgeMail -- generate simple SMTP session for testing email systems.
# $Id$

if [ $# != 3 ]; then
	echo Usage: forgemail host from to
	exit 1
fi

mailhost=$1
from=$2
to=$3

nc $mailhost 25 <<!
HELO forgemail.mail.tester
MAIL From:<$from>
RCPT To:<$to>
DATA
To: $to
Subject: Forwarding Test

This mail was sent via forgemail through smtpd.

quit
!
