#!/bin/sh

# Harvest the line (probably) describing the remotes' Mail Transfer Agent (opensmtpd, sendmail, ...)

for HOST
do

expect <<!
spawn telnet ${HOST} 25
expect 220
send "HELO test.please.ignore\r"
expect 250
send QUIT\r
expect 221
exit
!

done
