#!/bin/sh

# grepjs -- grep all the Java files for something...

# This is an example of find+xargs in a context where
# it's a better choice than 'grep -r' since
# grep would hit a lot of extraneous files.

patt=${1?"usage: grepjs pattern"}

cd $js || exit

find . -name '*.java' -print | xargs grep $patt
