#!/bin/sh -u

# grep the Java Cookbook for a given pattern
# $Id$

cd ~/book/javacook || exit

USAGE="$0 [-i][-l] patt ..."

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

FILES="ch?? ch???"

# Some UNIX strings(1)s use -o to include filenames, others use -f
# Some are too stupid to use either!!!

STRINGSOPT=""
GREPOPT=""

while getopts "il" opt 
do 
 	 case "$opt" in 
		i)	GREPOPT="$GREPOPT -i";;
		l)	echo 'The -l grep option does not work in "strings|grep"!' >&2
			exit 1 ;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

for patt in "$@"
do
	echo "==> $patt" >&2
	for file in ${FILES}
	# workaround for braindead Apple "Darwin" strings(1) with no -o option.
	do
		 echo -n $file
		strings ${STRINGSOPT} $file | egrep ${GREPOPT} "${patt}"
	done
done
