#!/bin/sh

set -x

DICT=/usr/share/dict/words

# grep ${DICT} for a word

function gw {
	rg "^$1"'$' ${DICT} || echo "No match"
}


case $1 in
	"") echo "Usage: $0 pattern|-c"
		exit 1;;
	-c)	while read patt; do gw $patt; done;;
	-r) rg $2 ${DICT} || echo "No match";;
	*)	gw "$1" ${DICT};;
esac
