#!/bin/sh

# nc demo -- get the type of web server somebody runs

METHOD=HEAD
if [ "$1" == "-a" ]; then
	METHOD=GET
	shift
fi
PORT=80
if [ "$1" == "-p" ]; then
	shift
	PORT=$1
	shift
fi

host=$1
resource=$2

echo ===== Trying ${host} =====
echo "${METHOD} /${resource} HTTP/1.1\nHost: ${host}\n" | nc ${host} ${PORT}
