#!/bin/sh

# nc demo -- get the type of web server somebody runs

METHOD=HEAD
if [ "$1" == "-a" ]; then
	METHOD=GET
	shift
fi
PORT=80
if [ "$1" == "-p" ]; then
	shift
	PORT=$1
	shift
fi

for host in ${*-localhost}
do
	echo ===== Trying ${host} =====
	echo "${METHOD} / HTTP/1.0\n" | nc ${host} ${PORT}
done
