#!/bin/sh

# import from an ancient camera that probably no longer exists, my Kodak DC-25

set -e

cd /mnt/DC25IMG 

DEST_DIR=$HOME/Pictures/`date +%Y%m%d`
if [ ! -d $DEST_DIR ]; then
	mkdir ${DEST_DIR}
fi

for FILE in *.K25
do
	PART=`expr $FILE : '\(.*H\).*'`
	echo $PART
	dcraw -c ${FILE} |pnmscale -xscale=0.75 |pnmtopng > ${DEST_DIR}/${PART}.png
done
