#!/bin/sh

cd /mnt/dcim/1* || exit

# make sure names have reasonable case, regardless of some cameras' affection for screaming caps.
(lcname -c *[A-Z]* | sh ) 2>/dev/null

DIR=pictures

SUBDIR=`date +%Y`/`date +%m`/`date +%d`

USAGE='$0 [-d yyyy/mm/dd]'

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "d:v" opt 
do 
 	 case "$opt" in 
		d)	SUBDIR=$OPTARG;;
		v)	VERBOSE=v;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

DEST_DIR=$HOME/${DIR}/${SUBDIR}

[ v == "${VERBOSE}" ] && set -x

echo 'jpg pictures\nmpg movies' | while read exten dir
do
	echo Checking for $exten and moving to $dir

	# Check if there are ANY $exten files in the camera
	GO=no
	for f in *.$exten; do if [ -f $f ]; then GO=yes; break; fi; done

	case ${GO} in
	yes)
		if [ ! -d ${DEST_DIR} ]; then
			mkdir -p ${DEST_DIR}
		fi
		echo Using ${DEST_DIR}

		cp -p *.${exten} ${DEST_DIR}/

		chown -R ian:wheel ${DEST_DIR}
		;;
	esac

done	# end of while read loop

if [ ! -d "${DEST_DIR}" ]; then
	echo "None found."
	exit 1
fi

echo "Uploaded:"
ls ${DEST_DIR}

echo -n "Erase [no,yes] " 
read oktoerase
case ${oktoerase} in
	y*)	rm -f *.jpg *.JPG *.mpg *.MPG
		;;
	*)	echo LEAVING PIX ON CAMERA
		;;
esac

cd ${DEST_DIR}
echo -n "View? [no,g)wenview,xv] " 
read view
case ${view} in
	g*)	gwenview . &;;
	x*)	xv * &;;
esac
