#!/bin/sh

set -e

cd /mnt/dcim/101hp417 || exit

echo 'jpg pictures\nmpg Movies' | while read exten dir
do
echo Checking for $exten and moving to $dir

# Check if there are ANY $exten files in the camera
GO=no
for f in *.$exten; do if [ -f $f ]; then GO=yes; break; fi; done

case ${GO} in
yes)

DEST_DIR=$HOME/${dir}/`date +%Y%m%d`
if [ -d $DEST_DIR ]; then
	DEST_DIR=`mktemp -d ${DEST_DIR}XXXXX`
else
	mkdir ${DEST_DIR}
fi
echo Using ${DEST_DIR}

cp -p *.${exten} ${DEST_DIR}/

chown -R ian:wheel ${DEST_DIR}
;;
esac

done	# end of while read loop

echo "OK to erase?" 
read ans
case ${ans} in
	yes)	rm *.jpg
		;;
	*)	echo LEAVING PIX ON CAMERA
		;;
esac
