#!/bin/sh

# Start a bunch of Java apps in a single JVM.
# Bug - originally, any one of them exits, and the whole thing dies;
# MainStarter does setSecurityManager that refuses System.exit(),
# but the wise folks at Java 'terminally deprecated' that with NO REPLACEMENT

JARDIR=${HOME}/lib
FILE=mytools-1.0.2-SNAPSHOT-jar-with-dependencies.jar

exec java -jar ${JARDIR}/${FILE} \
	workflow.BreakNagger

