#!/bin/sh -x

V=2

USAGE="$0 [-v n]"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "v:" opt 
do 
 	 case "$opt" in 
		v)	V=${OPTARG};;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

exec open ~/doc/javacook${V}.pdf
