#!/bin/sh

# Start a bunch of Java apps in a single JVM.
# bug - any one of them exits, and the whole thing dies;
# MainStarter should setSecurityManager that refuses System.exit()

JARDIR=${HOME}/lib
FILE=mytools-1.0.2-SNAPSHOT-jar-with-dependencies.jar

exec java -jar ${JARDIR}/${FILE} \
	jclipboard.JClipBoard \
	nag.Nagger \

