#!/bin/sh -u

# ;JAVA_CMD=${JAVA_CMD-$(javaPathHelper -c jeoip)}
JAVA_CMD=/usr/java/default/bin/java

case $# in
0)	echo >&2 "Usage: $0 patt [file[...]]"
	exit 1;;
esac

${JAVA_CMD} -classpath $HOME/lib/darwinsys.jar:$HOME/workspace/mytools/build jgrep.JGrep $*
