#!/bin/sh -u

# Grep will full regex, written in Java, until grep -P comes out of "experimental" and joins BSD

case $# in
0)	echo >&2 "Usage: $0 patt [file[...]]"
	exit 1;;
esac

java -classpath $HOME/lib/darwinsys-api-1.0.5.jar com.darwinsys.regex.JGrep "$@"
