#!/bin/sh

# Simplistic, hammer-based attempt to convert 80% of JUnit 3 tests to JUnit 4

sed '/^package/ {
a \
\
import static org.junit.Assert.*; \
import org.junit.*; \

}
/class/s/extends TestCase//
/public void test.*(/s//@Test &/
' $*
