#!/bin/sh

# rename last screen shot - only for os x

cd ~/Desktop

last="$(ls -t 'Screen Shot'* | head -1)"

case $1 in
	"") RIP=/tmp/screenshot.png;;
	*) RIP="$1";;
esac

mv "${last}" ${RIP}

echo "Was ${last}, now ${RIP}, USE IT OR LOSE IT"

open ${RIP}
