#!/bin/sh

# Try to convert legacy HTML tags to lower case.

sed \
	-e 's/HTML>/html>/' \
	-e 's/HEAD>/head>/g' -e 's/TITLE>/title>/g' \
	-e 's/<META/<meta/' -e 's/NAME=/name=/' -e 's/CONTENT=/content=/' \
	-e 's/<BODY/<body/' \
	-e 's/BODY>/body>/' \
	-e 's/BGCOLOR=/bgcolor=/' \
	-e 's/H\([1-6]>\)/h\1>/g' \
	-e 's/PRE>/pre>/g' \
	-e 's/<APPLET/<applet/g' \
	-e 's/CODE=/code=/g' \
	-e 's/WIDTH=/width=/g' \
	-e 's/ALIGN=/align=/g' \
	-e 's/HEIGHT=/height=/g' \
	-e 's/<A/<a/g' -e 's=</A>=</a>=g' -e 's/HREF=/href=/g' \
	-e 's/<IMG/<img/g' -e 's/SRC=/src=/g' \
	-e 's/<P>/<p>/g' -e 's?</P>?</p>?g' \
	-e 's/<TABLE/<table/g' \
	-e 's/\<COLGROUP\>/colgroup/g' \
	-e 's/<COL\>/<col/g' \
	-e 's/<TR\>/<tr/g' \
	-e 's/<TD\>/<td/g' \
	-e 's/<TH\>/<th/g' \
	-e 's/UL>/ul>/g' \
	-e 's/LI>/li>/g' \
	-e 's/KBD>/kbd>/g' \
	-e 's/ & /\&amp;/g'
	$*
