#!/bin/ksh -u

# lcname - rename file[s] to lower case
# Just makes a script - check it and, if OK, |sh
# -c (for cycle) moves X to j and j to x for use on
# msdos-like filesystems where you cant rename X to x

USAGE="$0 [-r][-n][-s] FILENAME [...]"

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

CYCLE=NO
SHELL=""

while getopts "nrv" opt 
do 
	case "$opt" in 
		r)	CYCLE=YES;;
		n)	SHELL="echo";;
		v)	VERBOSE=v;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

for f
do
	new="`echo $f | tr 'A-Z' 'a-z'`"
	case ${CYCLE} in
	NO) ${SHELL} mv "$f" "$new";;
	YES) ${SHELL} mv $f j; ${SHELL} mv j $new;;
	*)	echo huh??; exit 1;;
	esac
done 
