#!/bin/sh

# log2yyyymmdd - move a logfile to log.yyyymmdd
# must be run just BEFORE midnight

# Pick a day, any day (hopefully today).
DATE=`date +%Y%m%d`

# for each argument, save it in variable LOGFILE
for LOGFILE

do
        # and rename that puppy!
		echo ${LOGFILE} | sed -e "s/\(.*\)_log/mv & ${DATE}.\1.log/" | 
			sh -x
		touch ${LOGFILE}
		chown www:www ${LOGFILE}
done

if [ -f /webpages/htdocs/squad/logs/httpd.pid ]; then
	kill -HUP `cat /webpages/htdocs/squad/logs`
fi

gzip *.log

ls -l | mail ian@darwinsys.com # Ian - remove this after a day or two!

