#!/bin/sh

# params
OFFSITEDIR=log
INTERVAL=60
SIZE=800x600
F=$(mktemp /tmp/jumXXXXXXX)

while :
do
	fswebcam -r${SIZE} ${F}
	DEST=${OFFSITEDIR}/$(date +%H%M)
	# echo Copy to ${SERVER}:${DEST}
	scp ${F} ${SERVER}:${DEST}
	sleep ${INTERVAL}
done

