#!/bin/sh

# params
OFFSITEHOST=dos
OFFSITEDIR=log
INTERVAL=60
SIZE=800x600
F=$(mktemp /tmp/jumXXXXXXX)

while :
do
	fswebcam -r${SIZE} ${F}
	DEST=${OFFSITEDIR}/$(date +%H%M)
	scp ${F} ${OFFSITEHOST}:${DEST}
	sleep ${INTERVAL}
done

