#!/bin/sh

# create the mail aliases for a list.

echo	"## $1 mailing list"
echo	"# rewritten for MailMan 2.x $(nicedate)"
echo	"$1:              \"|/usr/local/lib/mailman/mail/mailman post $1\""
echo	"$1-admin:        \"|/usr/local/lib/mailman/mail/mailman admin $1\""
echo	"$1-bounces:      \"|/usr/local/lib/mailman/mail/mailman bounces $1\""
echo	"$1-confirm:      \"|/usr/local/lib/mailman/mail/mailman confirm $1\""
echo	"$1-join:         \"|/usr/local/lib/mailman/mail/mailman join $1\""
echo	"$1-leave:        \"|/usr/local/lib/mailman/mail/mailman leave $1\""
echo	"$1-owner:        \"|/usr/local/lib/mailman/mail/mailman owner $1\""
echo	"$1-request:      \"|/usr/local/lib/mailman/mail/mailman request $1\""
echo	"$1-subscribe:    \"|/usr/local/lib/mailman/mail/mailman subscribe $1\""
echo	"$1-unsubscribe:  \"|/usr/local/lib/mailman/mail/mailman unsubscribe $1\""
