#!/bin/sh

# Make the Hands-Ons from the Solutions, which are known to work.

set -x

JAR=$HOME/.m2/repository//com/darwinsys/makehandsons/1.0-SNAPSHOT/makehandsons-1.0-SNAPSHOT.jar

java -cp ${JAR}:$HOME/lib/darwinsys.jar \
	makehandsons.MakeHandsOns ${*-*solution}
