#!/bin/sh


case $# in
	3)	
		date=$1
		mileage=$2
		description=$3
		;;
	*)	echo "Usage: $0 [-|yyyy-mm-dd] mileage description" >&2
		exit 1
		;;
esac

if [ "$date" = "-" ]; then
	date=`date +%Y-%m-%d`
fi

echo "insert into employeecarusage(employee,type,date,mileage,description) 
                        values(1,'B','${date}',${mileage},'${description}');" |
				ssh rmn psql -d rejminet
