#!/bin/ksh -e

VOLUME_NAME="CD from Ian"
IMAGE=/tmp/mycd.iso
XCLUDES=""

set -x

USAGE="$0 [-v] old new"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "i:v:x:" opt 
do 
 	 case "$opt" in 
		i)	IMAGE="$OPTARG}";;
		v)	VOLUME_NAME="$OPTARG";;
		x)	XCLUDES="${XCLUDES} -x $OPTARG";;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

case "$*" in
	"") usage;;
	*) ;;
esac

# OK, make an image, don't yet burn it.

rm -f ${IMAGE}

case `uname` in
	Darwin*)
		hdiutil makehybrid -o ${IMAGE} -default-volume-name ${VOLUME_NAME} $*
		hdiutil attach ${IMAGE}
		ls /Volumes/${VOLUME_NAME}
		hdiutil burn -anydevice ${IMAGE}
		;;
	*BSD*)
		mkhybrid -R -r -J -f  \
			-V "${VOLUME_NAME}" -o "${IMAGE}"  \
			${XCLUDES} $*
		#mkisofs	-R -r -J -f -v "${VOLUME_NAME}" -o ${IMAGE} $*
		echo "Now you can make CD-ROMs using: burnit ${IMAGE}"
		;;
	*)
		echo "Do not know how to make CD on this system."
		;;
esac
