#!/usr/bin/env python3

# create links (default in HTML) from input like "https://darwinsys.com/ Ian Darwin's Web Site"
# add -n (no-list) to skip the <li>...</li> wrapper.
# add -t to open in a new Tab
# add -a to output in AsciiDoc(tor) instead of HTML
# add -h to output in HTML (default, not needed)

import sys,string,getopt

# echo a | mklinks
# <li><a href='a'>a</a></li>
# echo a b | mklinks
# <li><a href='a'>b </a></li>
# echo a b c | mklinks
# <li><a href='a'>b c </a></li>
# add -n to skip the <li>...</li> wrapper.

PRE="<li>"
POST="</li>"
TAB=""
mode="HTML"
try:
	# n for not-a-list, a for asciidoc, t for newTab
	options, filenames = getopt.getopt(sys.argv[1:], 'ahnt')
	# print("Options %s" % options)
	# print("Filenames %s" % filenames)
except:
	print("Usage: mklinks [-n][-a|-h][-t]")
	sys.exit(0)
for o, a in options:
	if o == '-a':
		mode="asciidoc"
	if o == '-h':
		mode="HTML"
	elif o == '-n':
		PRE="";
		POST=""
	elif o == '-t':
		TAB=' target="_blank"'

for line in sys.stdin.readlines():
	line=line[:-1] # kill stupid \n
	words=line.split();
	NF = len(words)

	if NF == 0:
		continue

	if mode == "HTML":
		if NF == 1:
			print("%s<a href='%s'%s>%s</a>%s" % (PRE, line, TAB, line, POST))
		if NF > 1:
			print("%s<a href='%s'>%s</a>%s" % (PRE, words[0], ' '.join(words[1:]), POST))
	elif mode == "asciidoc":
		if NF == 1:
			print("%s[%s]" % (line, line))
		if NF > 1:
			print("%s[%s]" % (words[0], ' '.join(words[1:])))
	else:
		print("Unknown output mode",mode)
