#!/usr/bin/env python

# create links (default in HTML) from input like "https://darwinsys.com/ Ian Darwin's Web Site"
# add -n (no-list) to skip the <li>...</li> wrapper.
# add -t to open in a new Tab
# add -a to output in AsciiDoc(tor) instead of HTML
# add -h to output in HTML (default, not needed)
# add -c captionsFile to use captions

import sys,string,getopt

# echo a | mklinks
# <li><a href='a'>a</a></li>
# echo a b | mklinks
# <li><a href='a'>b </a></li>
# echo a b c | mklinks
# <li><a href='a'>b c </a></li>
# add -n to skip the <li>...</li> wrapper.

PRE="<li>"
POST="</li>"
TAB=""
mode="HTML"
captions={}
try:
	# n for not-a-list, a for asciidoc, t for newTab, c for captions
	options, filenames = getopt.getopt(sys.argv[1:], 'achnt')
	# print("Options %s" % options)
	# print("Filenames %s" % filenames)
except:
	print("Usage: mklinks [-n][-a|-h][-t]")
	sys.exit(0)
for o, a in options:
	if o == '-a':
		mode="asciidoc"
	if o == '-h':
		mode="HTML"
	elif o == '-n':
		PRE="";
		POST=""
	elif o == '-t':
		TAB=' target="_blank"'
	elif o == '-c':
		try:
			with open("captions.txt") as input:
				for line in input:
					k,v = line.rstrip().split(',')
					# print(k,v)
					captions[k] = v
		except IOError as e:
			print("I/O Error reading captions file", a, e.args, file=sys.stderr)

for line in sys.stdin.readlines():
	line=line[:-1] # kill stupid \n
	words=line.split();
	NF = len(words)
	if NF == 0:
		continue
	filename = words[0]
	if captions.get(words[0]):
		line = captions[words[0]]

	if mode == "HTML":
		if NF == 1:
			print("%s<a href='%s'%s>%s</a>%s" % (PRE, filename, TAB, line, POST))
		if NF > 1:
			print("%s<a href='%s'>%s</a>%s" % (PRE, filename, ' '.join(words[1:]), POST))
	elif mode == "asciidoc":
		if NF == 1:
			print("link%s[%s]" % (filename, line))
		if NF > 1:
			print("%s[%s]" % (filename, ' '.join(words[1:])))
	else:
		print("Unknown output mode",mode)
