#!/usr/bin/awk -f

# mktour -- make a HTML guided tour of some sort.
# from some quaint and curious volume of forgotten lore
# (a.k.a. mktour.dat)

BEGIN {
	print "<html>"
	print "<h1>Quick Tour of Ian's Scripts</h1>"
	print "<p>This presents a small subset of what's here.</p>"
	print "<ul>"
}

/^$/ {
	next
	}

/^=/ {
	print "</ul>"
	$1 = ""
	print "<h2>" $0 "</h2>"
	print "<ul>"
	next
	}

	{
		n = split($0, words, / \- /)
		if (n != 2) {
			print "ERROR: Line " + NR + " not valid format" > "/dev/tty"
		}
		#print "<li><a href=\"" words[1] "\">" words[1] "</a>" words[2] "</li>"
		printf "<li><a href=\"%s\">%s</a> %s</li>\n", words[1], words[1], words[2]
	}

END {
	print "</ul>"
	print "<b>End of tour</b>"
	print "<hr/>"
	}
