#!/bin/sh -u

# mkwwwtemp == create a tmp file on www:/tmp
# so I can print using any ole browser while on the road

DESTDIR=/www/darwinsys/tmp
RANDOMIZE=no
case $1 in
	-r)	RANDOMIZE=yes; shift;;
esac

for file
do

	# SRC must be somethine we can reliably scp from after cd.
	case ${file} in
		/*)	SRC=$file;;
		*)	SRC=`pwd`/$file;;
	esac

	if [ "$file" == "index.html" ]; then
		RANDOMIZE=yes
	fi

	case ${RANDOMIZE} in
	yes)
		# Keep extention, since web server uses it for typing.
		ext=`echo ${file} | sed -e 's/.*\.//'`

		cd /tmp
		TMP=`mktemp XXXXXX`
		TARGET=${TMP}.$ext
		rm ${TMP}
		;;
	no)
		TARGET=$file
		;;
	*)
		echo "Merde, il pleut..." >&2
		;;
	esac

	set -e
	echo scp ${SRC} www.darwinsys.com:${DESTDIR}/${TARGET}
	     scp ${SRC} www.darwinsys.com:${DESTDIR}/${TARGET}

	ssh www.darwinsys.com chmod a+r ${DESTDIR}/* 2>/dev/null

	echo "$file is at http://www.darwinsys.com/tmp/${TARGET}"

done
