#!/bin/sh

# mkwwwtemp == create a tmp file on www:/tmp
# so I can print it while on the road

# set -x

for file
do

	# Keep extention, since web server uses it for typing.
	ext=`echo ${file} | sed -e 's/.*\.//'`

	case ${file} in
		/*)	SRC=$FILE;;
		*)	SRC=`pwd`/$file;;
	esac
	cd /tmp
	TMP=`mktemp XXXXXX`
	TARGET=${TMP}.$ext
	rm ${TMP}
	
	scp ${SRC} darwinsys.com:/www/tmp/${TARGET}

	ssh darwinsys.com chmod a+r /www/tmp/* 2>/dev/null

	echo "$file is in http://www.darwinsys.com/tmp/${TARGET}"

done
