#!/bin/sh -u

# mkwwwtemp == create a tmp file on www:/tmp
# so I can print it while on the road

 set -x

NORANDOM=no
case $1 in
	-r)	NORANDOM=yes; shift;;
esac

for file
do

	# SRC must be somethine we can reliably scp from after cd.
	case ${file} in
		/*)	SRC=$file;;
		*)	SRC=`pwd`/$file;;
	esac

	case ${NORANDOM} in
	no)
		# Keep extention, since web server uses it for typing.
		ext=`echo ${file} | sed -e 's/.*\.//'`

		cd /tmp
		TMP=`mktemp XXXXXX`
		TARGET=${TMP}.$ext
		rm ${TMP}
		;;
	yes)
		TARGET=$file
		;;
	*)
		echo "Merde, il pleut..." >&2
		;;
	esac
	
	scp ${SRC} darwinsys.com:/www/tmp/${TARGET}

	ssh darwinsys.com chmod a+r /www/tmp/* 2>/dev/null

	echo "$file is in http://www.darwinsys.com/tmp/${TARGET}"

done
