#!/bin/sh

# graphing using R

R --no-save <<!

png(filename="/home/ian/talk/mobihealth/images/marketshare.png", 
	width=500, height=500, pointsize=10)

names = c("Android", "iOS", "BlackBerry", "WinMo", "Other");
share = c(40,40,3,3,4)
market = data.frame(names,share) 

pie(share,
	labels=names,
	col=rainbow(length(share)))

title(main="Mobile Marketh Share, 2013")

# legend(x=10, y=200, legend=market[1], fill=rainbow(5))

dev.off()                  # Buffer flush

quit()
!

