#!/bin/sh

# Update an old Android project with new config files.

G=git # or "" if not using Git as your VCS
TMPL=~/git/AndroidTemplate

if [ ! -d $TMPL ]; then
	echo "Must have checked out https://github.com/IanDarwin/android_template into ~/git"
	exit
fi

if [ $# -ne 0 ]; then
	echo "Usage: cd project-home; $0 # no args"
	exit
fi

if [ ! -f build.gradle ]; then
	echo "Must start in Android project directory"
	exit
fi

# No Android Devel on Eclipse anymore, fbofw
$G rm -fr .project .classpath .settings 2>/dev/null

set -e # stop on error

if [ ! -d app ]; then
	echo "Project is very old, lacks app folder. Rearranging it for you."
	
	# Bluntly re-org a project that was built pre-"app"-subdirectory
	P=.

	mkdir -p $P/app/src/main

	$G mv    $P/AndroidManifest.xml        $P/app/src/main/AndroidManifest.xml

	$G mv    $P/src/main/java $P/app/src/main

	$G mv    $P/res $P/app/src/main/

	rmdir src
fi

echo "Now we will copy some files from $TMPL into $PWD"

cp ${TMPL}/build.gradle .

# add nl in case file ends w/o newline.
(echo; echo 'android.useAndroidX=true') >> gradle.properties

cp ${TMPL}/settings.gradle .
echo "NB Remember to edit the rootProject.name in settings.gradle"

cp app/build.gradle app/build.gradle.bak
cp ${TMPL}/app/build.gradle app/build.gradle
echo "NB Remember to edit the applicationID from settings.gradle.bak into settings.gradle"

cp ${TMPL}/gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.properties

echo "That is not a complete list of changes needed; see https://darwinsys.com/blog/2022-07-26-modernize-android/"
