#!/bin/sh

if [ ! -x /usr/local/sbin/shlight ]; then
	echo Make sure sharity-light is installed!
	exit 1
fi

sudo sharity mount //crwnstuh1/StudentD/dp925158 /home/dp925158 \
# -s CRWNSTUH1 -W STUDENT -U dp925158
