#!/bin/sh

# move my mailbox into /tmp so I can scp it atomically

doas mv /var/mail/idarwin /tmp
doas touch /var/mail/idarwin
doas chown idarwin /var/mail/idarwin
doas chgrp ian /var/mail/idarwin
doas chmod g+rw /var/mail/idarwin
echo "Your current mbox is /tmp/idarwin"
