#!/bin/sh

# Check for version updates. Somehow I can't remember mvn's syntax for this.

if [ -f pom.xml ]; then
	exec mvn versions:display-dependency-updates
else
	echo "$(pwd) not a Maven project, alas">&2
fi
