#!/bin/sh

# mvnproject - create a Maven project out of the air

ARTIFACT_ID=an-se-project

case $# in
	1)	ARTIFACT_ID=$1;;
	0)	;;
	*)	echo Usage: $0 [artifact-id] >&2
		exit 1
		;;
esac

if [ -d ${ARTIFACT_ID} ]; then
	echo "Error: ${ARTIFACT_ID} already exists" >&2
	exit 1
fi

echo "Project name will be ${ARTIFACT_ID}"

mvn archetype:generate \
	-DinteractiveMode=false \
	-DarchetypeGroupId=org.apache.maven.archetypes \
	-DarchetypeArtifactId=maven-archetype-quickstart \
	-DgroupId=com.darwinsys -DartifactId="${ARTIFACT_ID}" \
	-Dversion='1.0.0-SNAPSHOT'

cd ${ARTIFACT_ID} || exit
