#!/bin/sh

# mvnproject - create a Maven project out of the air

ARCHETYPE_GROUP_ID=org.apache.maven.archetypes
ARCHETYPE_ARTIFACT_ID=maven-archetype-quickstart
ARTIFACT_ID=an-se-project
GROUP_ID=com.darwinsys
VERSION='1.0.0-SNAPSHOT'

USAGE="$0 [-g groupId] [-a artifactId] [-v version] [-G archetypeGroupId] [-A archetypeArtifactId]"

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

while getopts "g:a:v:G:a:" opt 
do 
	case "$opt" in 
		a)	ARTIFACT_ID=$OPTARG;;
		g)	GROUP_ID=$OPTARG;;
		v)	VERSION=$OPTARG;;
		A)	ARCHETYPE_GROUP_ID=$OPTARG;;
		A)	ARCHETYPE_ARTIFACT_ID=$OPTARG;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

if [ -d ${ARTIFACT_ID} ]; then
	echo "$0: Error: ${ARTIFACT_ID} already exists" >&2
	exit 1
fi

echo "Project name will be ${ARTIFACT_ID}"

mvn archetype:generate \
	-DinteractiveMode=false \
	-DgroupId="${GROUP_ID}" \
	-DartifactId="${ARTIFACT_ID}" \
	-Dversion="${VERSION}" \
	-DarchetypeGroupId="${ARCHETYPE_GROUP_ID}" \
	-DarchetypeArtifactId="${ARCHETYPE_ARTIFACT_ID}"

cd "${ARTIFACT_ID}" || exit
