#!/bin/sh

case $# in 
	0) echo "Usage: $0 class [args]" >&2; exit 1;; 
	1) 
		CLASS=$1
		set -x
		mvn exec:java -Dexec.mainClass=${CLASS}
		;;
	*)
		CLASS=$1
		shift 1
		set -x
		mvn exec:java -Dexec.mainClass=${CLASS} -Dexec.args="$*"
		;;
esac


