#!/bin/sh

# mwd - maven wildfly:deploy

if [ ! -f pom.xml ]; then
	echo "No pom, so you bomb!"
	exit 1
fi

USAGE="$0 [-c] old new"

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

while getopts "cos" opt
do
	case "$opt" in
		c)	CLEAN=clean;;
		o)	OFFLINE=-o;;
		s)	SKIPTESTS=-DskipTests;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

mvn ${SKIPTESTS} ${OFFLINE} ${CLEAN} wildfly:deploy $*
