#!/bin/sh

p=/usr/ports

set -x

# Things that should be in packages

function do_it {
	for port
	do
		cd /usr/ports/$port; sudo make install
	done
}

# my own 
do_it textproc/idiff math/hoc
# Devel
do_it devel/gmake
# fonts
do_it freefonts ghostscript-fonts msttcorefonts
# print
do_it print/cups
# Useful
do_it sysutils/lsof archivers/zip # implies archivers/unzip 
do_it x11/xprompt x11/rxvt
do_it textproc/spiff 
# security
do_it security/crack security/nmap sysutils/pftop
# gfx/GUI
do_it graphics/giflib graphics/png graphics/tiff graphics/gtk+-1  graphics/xv
do_it print/gimp print/inkscape 
# GS
do_it graphics/ghostscript
# Textproc
do_it textproc/mgdiff textproc/xpdf
# Mail
do_it mail/mutt
# Java
do_it lang/kaffe-1.0
# webcam/communications stuff
do_it graphics/luvcview graphics/fswebcam x11/gnome-ekiga

# These take a LONG time
do_it devel/jdk/1.5 devel/jdk/1.6

cd $p/editors/openoffice; sh -x ./mk
