#!/bin/sh

# Try to install most of my standard packages

p=/usr/ports

[ -w / ] || { echo "Toot! Toot! You must be root!"; exit 1
}

set -x


function do_it {
	for port
	do
		pname=$(echo $port|sed -e 's=.*/==')
		pkg_add $pname || (cd /usr/ports/$port; make package; doas make install)
	done
}
# This takes a long time
pkg_add jdk maven


##################
# desktop-only goo
##################
if [ ! -z ${desktop} ]; then
	# bootstrap - X
	pkg_add xprompt rxvt-unicode desktop-file-utils # cwm is in base
	# fonts
	pkg_add ecoliercourt-fonts freefonts ghostscript-fonts msttcorefonts
	# print
	do_it print/cups
	# gfx/GUI
	do_it graphics/xv graphics/pwlib
	do_it print/gimp print/inkscape 
	# GS
	do_it graphics/ghostscript
	do_it editors/libreoffice
	# last few
	do_it games/micropolis
	# web and mail
	pkg_add firefox chromium mozilla-thunderbird mpack
	# Textproc
	pkg_add xpdf evince
	# webcam/communications stuff
	pkg_add luvcview fswebcam 
fi

if [ ! -z ${kde} ]; then
	# KDE (full) - brings in tons of depends
	pkg_add kde{libs,base,network,addons,artwork,multimedia,graphics,pim,toys}
	# GNOME (libs) - brings in tons of depends
	pkg_add gconf2 gnome-vfs2 gnome-mime-data glib2 dbug-glib libgnome2 evolution-data-server
fi

#################
# server-only goo
#################
if [ ! -z ${server} ]; then
	# depends on java
	pkg_add jenkins adb

	# Calendar server
	pkg_add radicale

	# Web/comms server
	pkg_add tomcat openfire

	# Mail server: uses opensmtpd + the following:
	pkg_add mailman dovecot
	pkg_add p5-Mail-SpamAssassin opensmtpd-extras-clamav 
fi

#####################################
# Remainder gets installed everywhere
#####################################

# some of my own 
pkg_add idiff hoc spiff 

# Bootstrap Devel/libs
pkg_add gmake dbus nss nspr ORBit2 libIDL
# Useful
pkg_add lsof zip unzip 
# security
pkg_add nmap pftop clamav

# database
pkg_add postgresl-server postgresql-client postgresql-contrib postgresql-docs

# network
pkg_add mutt openvpn nagios cnagios mrtg haproxy
mkdir /var/mrtg &&
	chown -R _mrtg /var/mrtg
# repo'd mrtg.conf will write to index.html

# devel
pkg_add cvs2svn

# has big depends (ImageMagick)
pkg_add llgal

pkg_add youtube-dl # desktop but also server for bandwidth
