#!/bin/sh

# Try to install most of my standard packages

p=/usr/ports

[ -w / ] || { echo "Toot! Toot! You must be root!"; exit 1
]

set -x


function do_it {
	for port
	do
		pname=$(echo $port|sed -e 's=.*/==')
		sudo pkg_add $pname || (cd /usr/ports/$port; make package; sudo make install)
	done
}

if [ ! -z ${desktop} ]; then
	# bootstrap - X
	pkg_add xprompt rxvt desktop-file-utils # cwm is in base
	# fonts
	pkg_add ecoliercourt-fonts freefonts ghostscript-fonts msttcorefonts
	# print
	do_it print/cups
	# gfx/GUI
	do_it graphics/png graphics/tiff graphics/gtk+-1  graphics/xv graphics/pwlib
	do_it print/gimp print/inkscape 
	# GS
	do_it graphics/ghostscript
	#cd $p/editors/openoffice; sh -x ./mk
	do_it editors/openoffice3
	# last few
	do_it games/micropolis
	# web and mail
	pkg_add chromium mozilla-thunderbird
	# Textproc
	pkg_add xpdf evince
	# webcam/communications stuff
	pkg_add luvcview fswebcam 
fi

if [ ! -z ${kde} ]; then
	# KDE (full) - brings in tons of depends
	pkg_add kde{libs,base,network,addons,artwork,multimedia,graphics,pim,toys}
	# GNOME (libs) - brings in tons of depends
	pkg_add gconf2 gnome-vfs2 gnome-mime-data glib2 dbug-glib libgnome2 evolution-data-server
fi

# some of my own 
pkg_add idiff hoc spiff 
# Bootstrap Devel/libs
pkg_add gmake dbus nss nspr ORBit2 libIDL
# Useful
pkg_add lsof zip unzip 
# security
pkg_add nmap pftop

# network
pkg_add mutt openvpn

# These take a LONG time
pkg_add jdk

# depends on java
pkg_add tomcat jenkins openfire maven # wildfly

# server only
pkg_add mailman
