#!/usr/bin/env python

import os,sys

# Like a shebang line, the %! magic must be on first line:

PSPROG = """%!PS-Adobe-1.0

% Prints a name tent, for average-length names

(Helvetica) findfont 150 scalefont setfont
gsave
100 700 moveto
270 rotate
(NAME) show
grestore

500 150 moveto
90 rotate
(NAME) show

showpage
"""
po = os.popen('lpr', 'w')

for name in sys.argv[1:]:
	po.write(PSPROG.replace("NAME", name))
	po.write("\n");
