#!/usr/bin/env python

# Print a name tent in big letters

import os,sys

# Like a shebang line, the %! magic must be on first line:

PSPROG = """%!

% %!PS-Adobe-2.0 EPSF-1.2
% %%BoundingBox: 0 0 612 792
% %%Resolution: 300
% %%EndComments

% Prints a name tent, for average-length names
% TODO getFontMetrics(NAME), / 2, add to xstart

(Helvetica) findfont 150 scalefont setfont
gsave
100 700 moveto
270 rotate
(NAME) show
grestore

500 150 moveto
90 rotate
(NAME) show

showpage
"""
#po = os.popen('lpr', 'w')
po = sys.stdout

for name in sys.argv[1:]:
	po.write(PSPROG.replace("NAME", name))
	po.write("\n");
