#!/bin/ksh

# Since I work on a few machines at many locations, this 
# script is a shortcut for setting the hostname.wireless to the correct one
# Setup: start with e.g., ln -s hostname.wireless hostname.rum0
# Then this script will ln from wireless to the current selection.

IF=iwn0
WAIT=70	# 	7.0 seconds

[ -w / ] || {
	echo be root to try $0
	exit 1
}

cd /etc

function showit {
	if [ -f hostname.wireless ]; then
		ls -l hostname.wireless
	fi
}
showit

oldPS3=PS3
PS3="Which wireless?"
select host in None $(cd /home/ian/.wifi; ls -d * | grep -v CVS)
do
	echo "==> host = ${host}"
	case ${host} in
	0)	break;; # do nothing
	n|None)	echo "Making yourself scarce, eh?"
		rm -f hostname.wireless
		break;;
	*)	echo You\'re at ${host}, eh?
		rm -f hostname.wireless	# clean up messes
		ln -sf /home/ian/.wifi/${host} hostname.wireless
		break;;
	esac
done
#stty $STTY
PS3=oldPS3
showit
sh /etc/netstart ${IF}
