#!/bin/sh

BUILD_DIR=workspace/darwinsys-api/build

set -x

cd
TARGET_DIRS="
lib
workspace/lhbooks/web/WEB-INF/lib
workspace/darwinsysweb/web/WEB-INF/lib
"

for dir in ${TARGET_DIRS}
do
	cp ${BUILD_DIR}/darwinsys.jar ${dir}/
done

for f in workspace/*/lib/darwinsys.jar
do
	cp ${BUILD_DIR}/darwinsys.jar ${f}
done

scp ${BUILD_DIR}/darwinsys.jar ${SERVER}:/www/javacookweb/
