#!/bin/ksh

# newgitrepo - create a new local GIT repo

cd /git || exit

case $# in
1)	;;
*)	echo Usage: $0 project
	exit 1
	;;
esac

[ -w / ] || {
	echo Ye be no talking lion!
	exit 1
}

NEWPROJ=${1:?"Usage: $0 newprojname"}

set -e # next steps must not fail

mkdir $NEWPROJ
cd    $NEWPROJ

git init --bare

chown -R ian .
chmod -R og+w .

echo "Your new project is ready:
git remote add origin git@git.darwinsys.com:$(pwd)"
