#!/bin/ksh

# mkport -- create a new port, in my ports directory

PORTSDIR=/usr/ports
MYPORTS=~/ports
TEMPLATE=/usr/ports/infrastructure/templates/Makefile.template

# prompt for these
echo -n "Program name (1 word)? "
read NAME junk
echo -n "Archive name (1 word, omit .tar.gz)? "
read DIST junk
echo -n "Archive site (directory URL, including ending slash)? "
read DNL junk
echo -n "Categories (1 or more words)? "
read CAT OTHERCATS
for f in ${CAT} ${OTHERCATS}
do
	if [ ! -d ${PORTSDIR}/${f} ]; then
		echo >&2 "mkport: $f is not a known category."
	fi
done

DIR=${MYPORTS}/${CAT}/${NAME}
mkdir -p ${DIR} || exit
if [ ! -d ${DIR} ]; then
	echo "$0: failed to mkdir ${DIR}" >&2
	exit 1
fi
cd ${DIR} || exit
MAKEFILE=Makefile
if [ -f ${MAKEFILE} ]; then
	MAKEFILE=Makefile.$$
	echo Makefile exists in ${DIR}, using ${MAKEFILE}
fi

sed \
	-e "/^PKGNAME=/s@???@$NAME@" \
	-e "/^DISTNAME=/s@???@${DIST}@" \
	-e "/^CATEGORIES=/s@???@$CAT@" \
	-e "/^MASTER_SITES/s@???@$DNL@" \
	\
	${TEMPLATE} > ${MAKEFILE}

mkdir pkg
touch pkg/PLIST
echo ${NAME} > pkg/COMMENT
echo ${NAME} > pkg/DESCR
set -x
make -k makesum extract
echo continue?
read y
vi ${DIR}/Makefile pkg/COMMENT pkg/DESCR
