#!/bin/ksh

# mkport -- create a new port, in my ports directory

PORTSDIR=/usr/ports
MYPORTS=~/ports

# prompt for these
echo -n "Program name (1 word)? "
read NAME junk
echo -n "Archive name (1 word, omit .tar.gz)? "
read DIST junk
echo -n "Archive site (directory URL, including ending slash)? "
read DNL junk
echo -n "Categories (1 or more words)? "
read CAT
for f in ${CAT}
do
	if [ ! -d ${PORTSDIR}/${f} ]; then
		echo >&2 "mkport: $f is not a known category."
		exit 1	# LAME
	fi
done

DIR=${MYPORTS}/${CAT}/${NAME}
mkdir -p ${DIR} || exit
cd ${DIR} || exit
MAKEFILE=Makefile
if [ -f ${MAKEFILE} ]; then
	MAKEFILE=Makefile.$$
	echo Makefile exists in ${DIR}, using ${MAKEFILE}
fi

sed \
	-e "s/^PKGNAME=/PKGNAME=$NAME/" \
	-e "s/^DISTNAME=/DISTNAME=	${DIST}/" \
	-e "s/^CATEGORIES=/CATEGORIES=$CAT/" \
	-e "s@^MASTER_SITES@MASTER_SITES = $DNL@" \
	\
	/usr/ports/infrastructure/templates/Makefile.template > ${MAKEFILE}

mkdir pkg
touch pkg/PLIST
echo ${NAME} > pkg/COMMENT
echo ${NAME} > pkg/DESCR
set -x
make -k makesum extract
echo continue?
read y
vi ${DIR}/Makefile pkg/COMMENT pkg/DESCR
