#!/bin/sh

# nukemailq - remove everything from the Mail Queue.
# This is rather sendmail-specific.

exit 1	# Not using sendmail here, but OpenSMTPD

cd /var/spool/mqueue || exit

for f
do
	echo "Nuking $f"
	grep -l "$f" qf* | sed -e 's/.\(.*\)/d\1 q\1/' | xargs rm -f
done
