#!/bin/sh -f

# simple emulation of MS-Windows' start command or OS X's open command:
# deduce type of file, start its application (backgrounded).

case $(uname) in
Darwin)	exec /usr/bin/open $@;;
# Presumably this is under cygwin or similar...
Windows) exec /c/program\ files/start $@;;
MINGW64*) exec /c/Program\ Files/Git/usr/bin/start $*;;
esac

if [ -x /usr/bin/xdg-open -o -x /usr/local/bin/xdg-open ]; then
	exec xdg-open "$@"
fi

BROWSER=NOT_SET
if [ -x /usr/bin/firefox -o -x /usr/local/bin/firefox ]; then
	BROWSER=FIREFOX
elif [ -x /usr/bin/chrome -o /usr/local/bin/chrome ]; then
	BROWSER=CHROME
else
	echo "Unknown browser; modify $0 to accomodate!"
	exit 1
fi

#echo "$*" > /tmp/start.log

# Tries to handle various browsers and various arguments
# Tries xdg-open from ports first if present, else $BROWSER
function browser {
	case ${BROWSER} in
	CHROME)
		case ${1} in
			# HTTP/HTTPS URL
			http*) exec chrome $1;;
			# local file: make full path and file:// URL
			*) case $1 in
				/*) exec chrome file://$1;;
				*) exec chrome file://${PWD}/$1;;
			esac
		esac
		;;
	FIREFOX)
		case ${1} in
			http*) exec firefox -remote "openURL(${1})"& ;;
			/*)  exec firefox -remote "openURL(file:${1})"& ;;
			*) exec firefox -remote "openURL(file:`pwd`/${1} )"& ;;
		esac
		;;
	*)	echo "No xdg-open found and no browser in default directory"
		exit 1
		;;
	esac
}

USAGE="$0 file ..."

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

APP=""

while getopts "a:v" opt 
do 
	case "$opt" in 
		a)	APP=${OPTARG};;
		v)	set -x;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

for f in "$@"
do
	if [ "${APP}" != "" ]; then
		${APP} $f
	else
	case "${f}"  in
		*.ai)	gimp "${f}" & ;;
		*.bmp|*.gif|*.jpg|*.jpeg|*.png|*.tif)	nsxiv "${f}" & ;;
		*.class) java `echo ${f}|sed 's/.class$//'` & ;;
		*.esl)	huckster ${f};;
		ftp://*) ftp "${f}" & ;;
		*.gz)	gunzip -v $f;;
		http:*|https:*|*.html|*.HTML?)
			browser ${f} & ;;
		*.mgp)
			mgp ${f};;
		*.mp3|*.ogg|*.avi|*.wav)
			mplayer ${f};;
		*.mp4|*.mpg|*.avi|*.mov|*.mkv)
			mplayer ${f};;
		*.pro)
			designer3 ${f} &;;
		*.pdf)	
			PDFERS="evince okular kpdf xpdf"
			FOUND=no
			for peeper in $PDFERS; do
				if [ -x /usr/bin/$peeper -o -x /usr/local/bin/$peeper ]; then
					${peeper} "${f}" &
					FOUND=yes
					break;
				fi
			done
			if [ ${FOUND} != "yes" ]; then
				echo "Can't find any Acrobatty readers for ${f}, trying browser" >&2
				browser $f &
			fi
			;;
		*.ps)	gs "${f}" & ;;
		# sla, svg, and swf must go before *.s??
		#*.svg)	browser "${f}" & ;;
		*.svg)	inkscape "${f}" & ;;
		*.sla)	scribus "${f}" & ;;	 # must come before soffice
		*.odt|*.doc|*.docx) exec soffice "$f" &;;
		*.odp|*.p[po]t|*.pptx) exec soffice "$f" &;;
		*.ods|*.xls|*.xlsx) exec soffice "${f}" &;;
		*.odg) exec soffice "${f}" &;;
		*.s??|*.o??) exec soffice "${f}" &;;
		*.sla)	scribus "${f}" & ;;
		*.txt)	notepad "${f}" & ;;
		*.xcf)	gimp "${f}" &;;
		*.Z)	uncompress "${f}" & ;;
		*)		echo "Not sure about ${f}'s format, trying browser..." >&2
				browser ${f};;
	esac
	fi
	sleep 5		# to avoid killing the machine
done
