#!/bin/ksh

# Open a url after removing garbage like spaces and mutt's + sign

case $1 in
	-n)	NOPRINT=true; shift;;
esac

URL=$(echo $1 | tr -d '+\r> '|sed 's/\^M//')

echo "Opening $URL"

if [ "${NOPRINT}" != true ]; then
	open $URL
fi
