#!/bin/sh

# run openbsd under qemu

cd ~/disks
# exec /usr/local/bin/qemu -cdrom ~/download/OpenBSD/snapshots/i386/install42.iso -hda openbsd.hd -boot c
exec /usr/local/bin/qemu -hda openbsd.hd -boot c
