#!/bin/sh
# overwrite	copy standard input to output after EOF
# 		final version
#		from Kernighan & Pike, The UNIX Programming Environment, p154.

opath=$PATH
PATH=/bin:/usr/bin:/usr/local/bin; export PATH

case $# in
	0|1)	echo 'Usage: overwrite file cmd [args]' 2>&1; exit 2;;
esac

file=$1; shift
new=/var/tmp/overw1.$$; old=/var/tmp/overw2.$$
trap 'rm -f $new $old; exit 1' 1 2 15	# clean up files

if PATH=$opath "$@" >$new
then
	cp $file $old	# save original file
	trap '' 1 2 15	# we are committed -- ignore signals
	cp $new $file
else
	echo "overwrite: $1 failed, $file unchanged" 1>&2
	exit 1
fi

rm -f $new $old
