#!/bin/sh

# plot of daily feedback data, using R
# if pace gets erased
# echo "pace=matrix(0,3,4)" | R

R --no-save <<!
data.entry(pace)
paceColors=c("blue","green","red")
x11()
split.screen(c(1,3))
screen(1)
barplot(pace[1,],col=paceColors,main="Tuesday")
screen(2)
barplot(pace[2,],col=paceColors,main="Wednesday")
screen(3)
barplot(pace[3,],col=paceColors,main="Thursday")
Sys.sleep(99999)
!
