#!/bin/sh

# pageunit - run the PageUnit web test software

# Before you run this, build the uber-jar as per the README, then cp the uber-jar to ~/lib/

# If the version number has grown, update V to match:

V=1.0.2-SNAPSHOT

java -jar ~/lib/pageunit-${V}-jar-with-dependencies.jar $*
