#!/bin/sh

# try to make a working fonts.dir and fonts.scale for a dir of PFB files

F=`mktemp /tmp/pfbmkfXXXXXXXXXX`

strings -f *.PFB | grep AdobeFont|tr ':' ' ' > $F

awk '
BEGIN {
	PATT = "%s -unk-%s-%s-o-normal--0-0-0-0-p-0-iso8859-1\n"
	OFILE="fonts.dir.tmp"
}
{
	n=split($3, arr, "-")
	if (n==1) 
		printf PATT, $1, $3, "medium" >>OFILE
	else if (n==2)
		printf PATT, $1, arr[1], arr[2] >>OFILE
	else
		print "*** INVALID ***", $0
}
' $F

wc -l < fonts.dir.tmp > fonts.dir
cat fonts.dir.tmp    >> fonts.dir

rm fonts.dir.tmp $F
