#!/bin/sh

# photgallery - generate index and thumnails for image dir

rm -f *thumb*

if [ ! -f index.head ]; then
	echo "[creating index.tail... you probably want to customize it]"
	cat>index.head <<!
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
>
<html>

<head>
	<title>Images... </title>
	<meta name="version"
		content="$Id$" />
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<link rel="stylesheet" type="text/css" href="/stylesheet.css" title="style"/>
	<meta http-equiv="Generator" content="Ian's photogallery ksh script"" />
</head>

<body bgcolor="white">

<h1>Images... </h1>
<p>This will be an introductory paragraph...
after you get around to customizing this page
</p>
<ul>
!
fi
cp index.head index.html
if [ ! -f index.tail ]; then
	echo "[creating index.tail]"
	cat>index.tail <<!
</ul>
</body>
</html>
!
fi

ls *.jpg *.png | sort | sed 's/\.\(...\)$/ \1/' | while read file ext
do
	echo $file $ext
	convert ${file}.${ext} -resize 64x64 ${file}-thumb.${ext}
	echo "<li><a href=\"${file}.${ext}\"><img border=\"0\" src=\"${file}-thumb.${ext}\"/>${file}.${ext}</a>" >> index.html
done

cat index.tail >> index.html
