#!/bin/ksh

# photocopy - use a scanner as a photocopier

PATH=/bin:/usr/bin:$PATH; export PATH

DEVICE=hp:/dev/ugen0

USAGE="$0 [-v] old new"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

COPIES=1
BRIGHT=0		# -100 .. +100
MODE=lineart

while getopts "cgbi:" opt 
do 
 	 case "$opt" in 
		c)	MODE=color;;
		g)	MODE=gray;;
		b)	MODE=lineart;;
		i)	BRIGHT=$OPTARG;;
		n)	COPIES=$OPTARG;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

scanimage -d ${DEVICE} --mode ${MODE} --brightness ${BRIGHT} |
	pnmtops | 
		lpr -#${COPIES}
