#!/bin/sh

# Clean up OpenBSD ports stuff

p=/usr/ports

echo "Removing conflict files"

find $p -name .#\* | xargs rm -f

echo "The following Makefiles may be messed:"

find $p -name Makefile|xargs grep -l '<<<'

