#!/bin/sh

# prep - output one word per line
# Intended for use in text processing scripts.
# Ancient unix magic but still works.
# Earlier versions were used as an example in various Bell Labs
# talks and papers by Lorinda Cherry; I made this version mid-1980's:

# Conceptually:
# cat $* |
# 	tr A-Z a-z | tr -cd 'a-z \n' | tr -s ' ' '\n'

# Now I use my own Java version:

exec java -cp ~/classes textproc.Prep $*

