#!/bin/sh

# print an x509 certificate in text form
# usually used for public keys in ".crt" files

for crt
do
	case $crt in
	*.crt)
		echo "=== crt ==="
		openssl x509 -text -noout -in $crt
		;;
	*.p12)
		echo "=== pkcs12 ==="
		openssl pkcs12 -in $crt -nodes |
			openssl x509 -noout -subject
		;;
	*.jks)
		echo "=== Java Keystore ==="
		keytool -v --keystore $crt --list
		;;
	*)
		echo "$0: $crt: unknown format (yet)"
		;;
	esac
done
