#!/bin/ksh -f

# pushenv -- send my important environment files to a new login

cd || exit

if [ $# -lt 1 -o $# -gt 2 ]; then
	echo "Usage: $0 host [user]" >&2
	exit 1
fi

HOST=$1
USER=${2-ian}

FILES=".AbiSuite .Xresources .efaxrc .exrc .fvwmrc .icbrc .kshrc .mailrc .myports .openwin-menu .profile .rhosts .sh-aliases .sh-env .sh-functions .stty .wine .wprc .xsession .kde scripts"

scp -r  ${FILES} ${USER}@${HOST}:

case ${USER} in
root)
	for f in /etc/sudoers
	do
		scp -r ${f} root@${host}:$f
	done
	;;
esac
