#!/bin/ksh -f

# pushenv -- send my important environment files to a new login

#FILES=".AbiSuite .Xresources .fvwmrc .icbrc .myports .openwin-menu .wine .wprc .xsession .kde"

if [ $# -lt 1 -o $# -gt 2 ]; then
	echo "Usage: $0 host [user]" >&2
	exit 1
fi

HOST=$1
USER=${2-ian}

DIRS=""

for f in ~/dotfiles ~/scripts 
do
	rm -f ${f}/.#?*
	DIRS="${DIRS} ${f}"
done

scp -r ${DIRS} ${USER}@${HOST}:
ssh -l ${USER} ${HOST} "cd dotfiles; make install"

