#!/bin/sh

# add good and bad guys to spamdb

# good guys
doas spamdb -a `awk '!/^#/{printf "%s ", $1}' /etc/mail/mywhite.txt`

# spam traps
while read address 
do doas spamdb -T -a "$address"
done < /etc/mail/myspamtraps.txt
