#!/bin/sh

# replace: replace str1 in files with str2, in place
# 		final version
#		from Kernighan & Pike, The UNIX Programming Environment.

PATH=/bin:/usr/bin:$PATH; export PATH

case $# in
	0|1|2)	echo 'Usage: replace str1 str2 files' 1>&2; exit 1;;
esac

oldPatt="$1"; newStr="$2"; shift; shift

for i
do
	overwrite $i sed "s!$oldPatt!$newStr!g" $i
done
