#!/bin/sh

# Request feedback from a customer.

case $# in
2|3);;
*) echo Usage: $0 customer email transaction >&2
   exit 1;;
esac

CUSTOMER=${1}
EMAIL=$2
TRANSACTION=$3

echo "To: ${CUSTOMER} <${EMAIL}>
Subject: Your eBay purchase of ${TRANSACTION}
Bcc: ian@darwinsys.com

Dear ${CUSTOMER}:

Thank you very much for your purchase: ${TRANSACTION}.

I am not a full-time eBay seller, just an individual who uses it to
sell a few unused items.  Nonetheless, I like to keep my feedback
scores up. If you are happy with your purchase when it arrives,
please give me positive feedback. If not, or if you are asked the
detailed Star ratings and there is any reason you cannot give five
stars on all fronts, please let me know before you enter it so I may
have take the opportunity to address the outstanding issue!

The quickest way to leave feedback is to login to eBay, click on My eBay,
and choose Purchase History. Items that you haven't left feedback for will
have a "Leave Feedback" link at the far right. I do not provide a link
here because you generally should not trust links in email from people 
you don't know really well :-)

Again, thank you for purchasing from me on eBay.

Ian F. Darwin
ian@darwinsys.com
" > /tmp/request$$

vi /tmp/request$$

cd /tmp
sendit request$$
