#!/bin/sh

# reload a PF table

[ -w / ] || {
	echo "Be root for $0"
	exit 1
}

for TBL
do

	echo "Table ${TBL} before:"
	pfctl -T show -t ${TBL} || exit

	doas pfctl -T replace -t ${TBL} -f /etc/${TBL}

	echo "Table ${TBL} after:"
	pfctl -T show -t ${TBL} || exit

done
