#!/bin/sh

# emulate an ancient command to help with finger retraining

echo "Groovy, mon! It's 1984 all over again"
echo "(except it's really $(date), so we're bringing you into the 21st Century)."

open https://news.google.com/
