#!/bin/sh

# make, and sign, an RSA server certificate

set -v

openssl genrsa -out /etc/ssl/private/server.key 1024
openssl req -new -key /etc/ssl/private/server.key \
	-out /etc/ssl/private/server.csr
openssl x509 -req -days 365 -in /etc/ssl/private/server.csr \
	-signkey /etc/ssl/private/server.key -out /etc/ssl/server.crt
