#!/bin/sh

# Scan an image from a scanner - see scanimage

MODE=color

mkdir ~/tmp 2>/dev/null 

# do not change to -t, must be in /home
TMP=`mktemp ${HOME}/tmp/scanXXXXXXXX`

scanimage --mode=${MODE} --format=tiff > ${TMP} &&

echo "Your scan is complete; saved as ${TMP}"
