#!/bin/sh

# send a file via sendmail

set -x

function copyit {
	scp $f darwinsys.com:/tmp && mv $f $f.sent
	ssh darwinsys.com scripts/sendit /tmp/$f
}

for f
do

	if [ -f $f ]; then
		case `hostname` in
		darwinsys.com|www.darwinsys.com|darian.darwinsys.com)
			sendmail -v -t < $f && mv $f $f.sent
			;;
		*)	copyit $f
			sleep 15
			;;
		esac
	else
		echo "$0: No file $f" >&2
	fi

done
