#!/bin/sh

JARHOME=~ian/lib
JAR=sendsms-1.0.0-SNAPSHOT-jar-with-dependencies.jar

case $# in
0|1)	echo "Usage: $0 nameber message..." 2>&1
	exit 1
	;;
esac

PHONENUM=$1
shift
MESSAGE="$@"

echo + java -jar ${JARHOME}/${JAR} $PHONENUM "${MESSAGE}"

java -jar ${JARHOME}/${JAR} $PHONENUM "${MESSAGE}"
