#!/bin/sh

# send a file via sendmail

set -x

function copyit {
	scp $f mail.darwinsys.com:/tmp && mv $f $f.sent || exit 1
	ssh darwinsys.com scripts/sendit /tmp/$f || exit 1
}

for f
do

	if [ -f $f ]; then
		case `hostname` in
		darwinsys.com|www.darwinsys.com|darian.darwinsys.com)
			exec sendmail -v -t < $f && mv $f $f.sent
			;;
		*)	copyit $f
			;;
		esac
	else
		echo "$0: No file $f" >&2
	fi

done
