#!/bin/ksh

# send a file via sendmail

USAGE="$0 [-h host] msgFile"


function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

HOST=${SERVER}

while getopts "h:" opt 
do 
 	 case "$opt" in 
		h)	HOST=$OPTARG;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

set -x

for f
do

	if [ -f $f ]; then
		case `hostname` in
		darwinsys.com)
			# use generic sendmail interface
			exec sendmail -v -t < $f && mv $f $f.sent
			;;
		*)	set -e
			scp $f ${HOST}:/tmp && mv $f $f.sent || exit 1
			ssh ${HOST} scripts/sendit /tmp/$f || exit 1
			mv $f $f.sent
			;;
		esac
	else
		echo "$0: No file $f" >&2
	fi

done
