#!/usr/bin/env python

# put up a Tk GUI for composing and sending email via mpack

from Tkinter import Tk,Button,Label,Entry
import sys,os

global recips, subject

rootWindow = Tk()

if sys.argv[1][0] == '/':
	file = sys.argv[1]
else:
	file = os.curdir + '/' + file

#case $file in
#	*.jp*g)	SUBTYPE=jpeg;;
#	*.gif)	SUBTYPE=gif;;
#	*.png)	SUBTYPE=png;;
#	*)	echo Unknown image type for $IMAGE
#		exit 1;;
#esac

label = Label(rootWindow, text="Send Image %s" % file)
label.pack()

SUBTYPE = "jpg"	# XXX compute this!

def handler(*args):
	global recips
	cmd = 'mpack -s "%s" -c image/%s %s %s' % (
		subject.get(), SUBTYPE, file, recips.get())
	print cmd
	os.system(cmd)
	sys.exit(0)

Label(rootWindow, text="To:").pack()
recips = Entry(rootWindow)
recips.pack()

Label(rootWindow, text="Subject:").pack()
subject = Entry(rootWindow, text="Subject")
subject.pack()

button = Button(rootWindow, text='Send', command=handler);
button.pack()

rootWindow.mainloop()
