#!/usr/bin/env python

from Tkinter import Tk,Button,Label,Entry
import sys,os

global recips, subject

rootWindow = Tk()

file = sys.argv[1]
#case $file in
#	*.jp*g)	SUBTYPE=jpeg;;
#	*.gif)	SUBTYPE=gif;;
#	*.png)	SUBTYPE=png;;
#	*)	echo Unknown image type for $IMAGE
#		exit 1;;
#esac

label = Label(rootWindow, text="Send Image %s" % file)
label.pack()

SUBTYPE = "jpg"	# XXX compute this!

def handler(*args):
	global recips
	cmd = 'mpack -s "%s" -c image/%s %s %s' % (
		subject.get(), SUBTYPE, file, recips.get())
	print cmd
	os.system(cmd);

recips = Entry(rootWindow, text="To")
recips.pack()

subject = Entry(rootWindow, text="Subject")
subject.pack()

button = Button(rootWindow, text='Send', command=handler);
button.pack()

rootWindow.mainloop()


