#!/bin/sh

# pixsetdate - set the "original" timestamp on jpeg or other exif image

DATE="1970:06:06"
TIME="12:00:00"
OWNER="Ian F. Darwin"

PATH=/bin:/usr/bin:$PATH; export PATH

USAGE="$0 [-d yyyy:mm:dd][-t hh:mm:ss] image ..."

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "d:t:" opt 
do 
 	 case "$opt" in 
		d)	DATE=$OPTARG;;
		t)	TIME=$OPTARG;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

YEAR=$(expr $DATE : '\([12][0-9][0-9][0-9]\)')

exiv2 \
	-M"set Exif.Photo.DateTimeOriginal ${DATE} ${TIME}" \
	-M"set Exif.Image.Copyright Copyright ${YEAR} ${OWNER}" \
		$*
