#!/bin/sh

# set the scanned date, since the Wolverine scanner is too stupid to maintain the date and time

USAGE="$0 YYYY:MM:DD file..."

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "d:" opt 
do 
 	 case "$opt" in 
		h)	usage;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

if expr "$1" : '[0-9]\{4\}:[01][0-9]:[0123][0-9]' >/dev/null; then
	DATE=$1
	shift
else
	DATE="$(date +%Y:%m:%d)"
	echo "$0: $1 is not a date, using $DATE" >&2
fi


exiv2 -M"set Exif.Photo.DateTimeDigitized $DATE 12:00:00" $*
