#!/bin/sh

# connect to a Skytap instance after you've downloaded its .rdp file
# The rdp file contains a line like so:
# full address:s:services-uscentral.skytap.com:17427

echo "Make sure remote is powered up"

LOGIN=user
LOGIN=student
PASS=pw
PASS=studentpw

tr -d '\015' < ${1-~/Downloads/*.rdp} |
awk -F: '
$1 == "full address" {
	HOST=$3
	PORT=$4
}
END {
	cmd = sprintf("rdesktop -u %s -p %s -k en-us -a 8 %s:%s", "'$LOGIN'", "'$PASS'", HOST, PORT)
	print cmd
}' | 
	sh -x

