#!/bin/sh

# SQLRunner - Main Version

# Change this to where you have the darwinsys.jar file installed
PROGRAM_JARS=${HOME}/lib/sqlrunner.jar:${HOME}/lib/darwinsys.jar

# Add Driver JAR files to CLASSPATH
for driver in hsqldb postgresql-8.1dev-401.jdbc3 db2jcc db2jcc_license_cu
do
	DRIVER_JARS=${DRIVER_JARS}:${HOME}/lib/$driver.jar
done

set -x

export CLASSPATH="${PROGRAM_JARS}:${DRIVER_JARS}"

case $1 in
-cli)	shift; java com.darwinsys.sql.SQLRunnerCLI $*;;
*) java com.darwinsys.sql.SQLRunnerGUI $*;;
esac
