#!/bin/sh

# SQLRunner - Main Version

JVMOPTS="-Djava.net.preferIPv4Stack=true"

# Change this to where you keep your jars
JAR_DIR=$HOME/lib

# Add Driver JAR files to CLASSPATH
for jar in darwinsys-api \
	hsqldb postgresql ojdbc14 sqlitejdbc* dbfdriver
do
	if [ -f ${JAR_DIR}/${jar}*.jar ]; then
		D=$(echo ${JAR_DIR}/${jar}*.jar)
		CLASSPATH=${CLASSPATH}:${D}
	else
		echo "Not adding ${JAR_DIR}/${jar}*.jar"
	fi
done

set -x

case $1 in
-cli)	shift; java ${JVMOPTS} -classpath ${CLASSPATH} com.darwinsys.sql.SQLRunnerCLI $@;;
*) java ${JVMOPTS} -classpath ${CLASSPATH} com.darwinsys.sql.SQLRunnerGUI $*;;
esac
