#!/bin/sh

# make, and sign, RSA or DSA server certificate

DIR=/etc/ssl
EXP_DAYS=36500 # 100 years, who wants to renew yearly?
NAME=server
USAGE="$0 [-d DIR][-n NAME][-v]"
GENVERB=gendsa
BITZ=2048

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

while getopts "d:e:n:svz:" opt 
do 
	case "$opt" in 
		d)	DIR=$OPTARG;;
		e)	EXP_DAYS=$OPTARG;;
		n)	NAME=$OPTARG;;
		s)	SIGN=true;;
		v)	set -x;;
		z)	BITZ=$OPTARG;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

mkdir -p ${DIR}/private || {
	echo "Mkdir failed, do you have permission?" >&2
	exit 1
}

# Generate key pair
openssl ${GENVERB} -out ${DIR}/private/${NAME}.key $BITZ

# Create signing request
openssl req -new \
	-days $EXP_DAYS \
	-key ${DIR}/private/${NAME}.key \
	-out ${DIR}/private/${NAME}.csr

# Self-sign the key, if requested
${SIGN} &&
	openssl x509 -req -days 36500 -in ${DIR}/private/${NAME}.csr \
		-signkey ${DIR}/private/${NAME}.key -out ${DIR}/${NAME}.crt
