#!/bin/sh

# Rearrange Pictures to strict date-order filing. 

# USE WITH CAUTION! USE AT OWN RISK! Failures may lose pictures - take a backup first

# Looks for this in exiv2 output:
# Image timestamp : 2020:08:06 09:30:08

# Bomb on first failure, try to avoid losing pix:
set -e

# Make sure we in right folder
cd ~/Pictures

for f in $*
do
  exiv2 $f |      
	awk '$0 ~ /^Image timestamp/ {
		gsub(":","/",$4)
		printf "if [ ! -d %s ]; then mkdir -p %s; fi\n", $4, $4
		print "mv '$f' " $4 "/"
	}'
done
