#!/bin/ksh -f

# Rearrange Pictures to strict date-order filing by moving into directory with yyyy/mm/dd

# Can NOT use exiv2 "--rename fmt" because that has only one-second resolution,
# and since about 2000 A.D., cameras can take >1 pix per second.

# USE WITH CAUTION! USE AT OWN RISK! Failures may lose pictures - take a backup first

USAGE="$0 [-v] \$PWD/file[...]"

# Sample entry: Image timestamp : 2023:07:28 19:46:53
# Sample entry: Exif.Image.DateTime Ascii 20  2023:07:09 13:02:10
# Note that in both, $4 is the yyyy:mm:dd that we use in awk below.

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

# Make sure we are in right folder
cd ~/Pictures

java --enable-preview -jar /home/ian/lib/imagelibtools-1.0.0-SNAPSHOT-jar-with-dependencies.jar "$@"
