#!/bin/sh

# Create system status html page

echo "<h1>System status at `date`</h1>"

tag() {
	echo "<$1>"
}

# heading text
heading() {
	tag hr/
	echo "<h2><a name=\"$1\">$1</a></h2>"
}

heading who Who
tag pre
who
tag /pre

heading top
tag pre
top | head -25
tag /pre

heading swap
tag pre
swapctl -l
tag /pre

heading df
tag pre
df -h
tag /pre

heading netstat
tag pre
netstat -na
tag /pre

