#!/bin/sh

# show how old this OpenBSD system is

uptime

sysctl kern.version

# Tweak ls of libc.so as long as .so.9?.* matches
ls -Ll /usr/lib/libc.so.1??.? | tail -1 
ls -Ll /bin/cat /usr/X11R6/bin/X 
ls -Ll /usr/share/man/{mandoc,whatis}.db 2>/dev/null
