#!/bin/sh

# create the canonical hello-world app in Java

cat>t.java <<!
public class t {
	public static void main(String[] unused) {
		System.out.printf("Hello\n");
	}
}
!

# And even try running it!

jr t
