#!/bin/sh

# This script has a bunch of names. YOU MUST only edit under the name
# "tcenable", or you will surely lose all your work!

HOST=localhost	# TODO getopt -v virtualhost

cd $HOME/tomcat/conf/Catalina/${HOST} || exit

case $0 in
	*tcdisable)
		mv $1.xml $1.xml-not
		;;
	*tcenable)
		mv $1.xml-not $1.xml
		;;
	*tcedit)
		vi $1.xml
		;;
	*tclist)	
		# work done below
		;;
	*) echo "Urk! Unknown alias $0" >&2; exit 1;;
esac

ls
