#!/bin/sh

# View the TeslaCam videos
# start in directory ABOVE the TeslaCam folder, eg. /Volumes/TESLA_128GB

cd TeslaCam 

for f in SavedClips/* SentryClips/*
do
	echo ==== $f ====
	# Mostly saved b/c of last minute of video, so just look there
	echo $*
	ls -rt ${PWD}/$f/* | head -4 | grep front | xargs open
	# Most of them are useless, default to rm
	/bin/echo -n "rm -r $f ?"
	read ans junk
	case $ans in
		n*)	;;
		*) rm -rf $f;;
	esac
done
