#!/bin/ksh -f

case $# in
1);;
*) echo "Usage: $0 openhost" >&2
	exit 1
	;;
esac

OPENHOST=$1

# Ensure Java variables set correctly even if invoked non-interactively
. ~/.sh-java

set -x
cd ~/javasrc/email
java TestOpenMailRelay ${OPENHOST}

sleep 10
