#!/bin/sh

# notepad - Run my simple Java reimplementation of NotePad

JAVA_CMD=${JAVA_HOME-/usr/}/bin/java
JAVA_CMD=/usr/local/jdk-17/bin/java

PROJECT=tinypad
MAINCLASS=com.darwinsys.tinypad.TinyPad 

${JAVA_CMD} -classpath ~/lib/darwinsys.jar:$ws/${PROJECT}/target/classes ${MAINCLASS} "$@" &

