#!/bin/sh

function usage {
	echo "Usage: $0 + topic | - | e"
	exit 1
}

case $# in
	0|1)	usage;;
esac

DIR=$HOME/.timesheet/
LOGFILE=${DIR}/`date +%Y-%m`-$2
CATSFILE=${DIR}/time.properties

case "$1" in
	e|-e)	exec ${VISUAL-vi} ${LOGFILE};;
	-c)		cat ${CATSFILE};;
	start|in|on|begin|'+')	code='+'; shift
			case "$#" in
				0) usage;;
			esac
			;;
	end|off|out|"-")		code='-'; shift;;
	-t|-l|tail)	exec tail ${LOGFILE};;
	""|*)	usage;;
esac

echo "`date +%Y-%m-%d' '%H%M` $code $*" >> ${LOGFILE}
