#!/bin/sh

if [ "-s" == "$1" ]; then
	MODE=-s
	shift
fi

YEAR_MONTH=${1?"Usage: $0 YYYY-MM"}

java -classpath $ws/mytools/build:$ws/mytools/lib/poi-2.5.1-final-20040804.jar invoicing/DateCompactor ${MODE} ~/.timesheet/${YEAR_MONTH}-*
