#!/bin/sh

# TKR - monthly report

if [ "-s" == "$1" ]; then
	MODE=-s
	shift
fi

YEAR_MONTH=${1?"Usage: $0 YYYY-MM"}
TSDIR=${HOME}/.timesheet/

if [ ! -d ${TSDIR} ]; then
	echo $TSDIR is missing and presumed lost!!
	exit 1
fi

for f in ${TSDIR}/*.bak
	do mv $f /tmp/
done

java \
	-classpath $ws/mytools/build:$ws/mytools/lib/poi-2.5.1-final-20040804.jar \
	invoicing/DateCompactor ${MODE} ${TSDIR}/${YEAR_MONTH}-*
