#!/bin/sh

# Enter or list the todo database

PRIO=2

case $# in

0)	CMD="select id,priority,name from todo where status != 'c' order by priority asc, name asc;"
	;;

*)	case $1 in
	-d) CMD="delete from todo where id = ${2};";;
	*)  CMD="insert into todo(name,priority) values('$*', '$PRIO');";;
	esac
	;;

esac

ssh dos.new psql -d todo <<! |more 
$CMD
!
