#!/bin/sh

# Enter or list the todo database

PRIO=MEDIUM # Top=0, High=1, Medium=2, Low=3
CONTEXT=null
TYPE=1 # 1 = TODO, 2 = recurrant, 3 = reminder
MORE='more -e'
REST=""
VERB=insert
case $# in
	0) VERB=LIST;;
esac

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

USAGE="$0 [-c context][-p prio][-d id] [-t type] description of some task"
while getopts "c:d:lp:t:v" opt 
do 
	case "$opt" in 
		c)	CONTEXT=$OPTARG;;
		d)	VERB=delete
			ID=$OPTARG
			;;
		l)	VERB=LIST;;
		p)	PRIO=$OPTARG;;
		t)	TYPE=$OPTARG;;
		v)	#ignored
			;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

# Convert Priorities to int
case ${PRIO} in
	TOP)	PRIO=0;;
	HIGH)	PRIO=1;;
	MEDIUM)	PRIO=2;;
	LOW)	PRIO=3;;
	[0123])	;; # Already there
	*)		echo Warning: Priority $PRIO unrecognized;;
esac

# Should do same for Context?

case ${VERB} in
	LIST)
		CMD="select t.id, t.priority, (select c.name as Context from context c where t.context_id = c.id), t.name from todo t where status != 3 ${REST} order by t.priority asc, t.name asc;"
		POST="| sed 1,2d"
		;;
	delete) CMD="delete from todo where id = ${ID};";;
	insert) CMD="insert into todo(name,type_id,priority) values('$*', '$TYPE', '$PRIO');";;
esac

echo $CMD |
case $(hostname) in
	darwinsys.com)
		eval psql -d todo $POST |${MORE}
		;;
	*)
		eval ssh dos psql -d todo $POST |${MORE}
		;;
esac
