#!/bin/sh

# unJAV -- move .JAV files to .java, after cvsing on a dosfs under uNIX

ls *.JAV |xargs egrep 'public (class|interface)' /dev/null | tr : ' ' | 
	awk '{print "mv", $1, "tmp && mv tmp", $4 ".java"}' | cat
