#!/bin/sh

# unmv - undo a mv command, for use with shell history.

if [ $# -ne 2 ]; then
	echo "$0: this version does NOT support wildcards!" 2>&1
	exit 1
fi

if [ -d $2 ]; then
	mv $2/$1 $1
else
	mv $2 $1
fi

