#!/bin/ksh

# untar - list or extract a tar

PATH=/bin:/usr/bin:$PATH; export PATH

USAGE="$0 -l|-t|-x [-v][-z] old new"

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

MAIN_OP=x
VERBOSE=
while getopts "ltvxz" opt 
do 
	case "$opt" in 
		l|t)	MAIN_OP=t;;
		v)	VERBOSE=v;;
		x)	MAIN_OP=x;;
		z)	ZLIB=z;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

for f
do
	ZLIB=""
	case "$f" in
	*.tar.gz|*.tgz|*.tz)	ZLIB=z;;
	esac
	tar ${MAIN_OP}${VERBOSE}${ZLIB}f $f
done
