#!/bin/sh

# update - update a repo whether it be CVS, Svn, Git, ...

do_update() {
if [ -d CVS ]; then
	echo Updating $(pwd) via CVS
	if [ "" == "${CVSROOT}" ]; then
		echo "Go ahead and make my CVSROOT!"
		sleep 1
		. ~/obscripts/dotscripts/cvsr
	fi
	echo Updating CVS from ${CVSROOT}
	cvs -d $CVSROOT update -PAd $*
elif [ -d .svn ]; then
	echo Updating $(pwd) via Svn
	svn update
elif [ -d .git ]; then
	echo Updating $(pwd) via git
	git pull
else
	echo "Sorry, dunno how to update $(pwd)"
fi
}

if [ $# -eq 0 ]; then
	do_update;
else
	for f
	do
		(cd $f
		echo chdir\'d to $PWD
		do_update
		)
	done
fi
