#!/bin/ksh 

if [ ! -w / ]; then
	echo "Run with more privileges" >&2
	exit
fi

if [ -f /etc/mail/aliases ]; then
	vi  /etc/mail/aliases
elif [ -f /etc/aliases ]; then
	vi  /etc/aliases
else
	echo "No alias file" >&2
fi
