#!/bin/sh -u

set -x 

VMAIL_DIR=/var/spool/asterisk/voicemail/default/201/INBOX

ssh rmn doas chmod g+r ${VMAIL_DIR}/*

scp rmn:${VMAIL_DIR}/* /tmp

for v in /tmp/*.gsm
do
	cat $(echo $v|sed 's/gsm$/txt/')
	gsmplay $v
done

echo remove all?
read ans
case ${ans} in
	y*)	ssh rmn doas rm ${VMAIL_DIR}/*
		;;
esac

