#!/bin/ksh

# watchlog - consolidate watchlog functionality.

PATH=/bin:/usr/bin:$PATH; export PATH

TAIL_PROG=tail

USAGE="$0 [-f] logname"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

NUM=""
MORE=cat
while getopts "fmn:v" opt 
do 
 	 case "$opt" in 
		f)	TAIL_F=-f;;
		m)	MORE="more";;
		n)	NUM=-${OPTARG};;
		v)	TAIL_PROG=${VISUAL-vi};;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

#if [ $# -eq 0 ]; then
#	usage
#fi

for f
do
	case $f in
		-*) ;;
		"")	echo "Usage: $0 logname" >&2; exit 1;;
		cdr)	LOG=/var/log/asterisk/cdr-csv/Master.csv;;
		cvs|chang*) LOG=/cvs/CVSROOT/ChangeLog ;;
		cups)	LOG=/var/log/cups/error_log;;
		daem*|ppp) LOG=/var/log/daemon ;;
		ftp)	LOG=/var/log/xferlog;;
		http|web|www) LOG=/var/www/logs/access_log ;;
		httperr|weberr) LOG=/var/www/logs/error_log ;;
		icb|hackers)	LOG=~/hacklog/`date +%Y-%m`;;
		port*s)	LOG=~/portslog/`date +%Y-%m`;;
		jserv)	LOG=/var/www/logs/mod_jserv.log;;
		lp*)	LOG=/var/log/lpd-errs;;
		mail)	LOG=/var/log/maillog ;;
		mess*)	LOG=/var/log/messages ;;
		nagios)	LOG=/var/log/nagios/nagios.log;;
		nohup)	LOG=${HOME}/nohup.out;;
		ob) watchlog -f cvs & watchlog -f icb & watchlog -f ports&
			exit
			;;
		pf|fw)	exec tcpdump -n -e -ttt -i pflog0;;
		ppp|chat)	LOG=/var/log/chat ;;
		secure)	LOG=/var/log/secure ;;
		snort)	LOG=/var/log/snort/alert ;;
		spam) watchlog -f mail & watchlog -f daemon&
			exit
			;;
		squid)	LOG=/var/squid/logs/access.log;;
		tomcat)	exec xtail /var/tomcat/logs;;
		vnc)	LOG=~/.vnc/*.log;;
		www)	exec xtail /var/log /var/tomcat/logs;;
		x|X)	LOG=/var/log/XFree86.0.log;;
		x|xs|xsess*|xerr*) LOG=~/.xsession-errors;;
		*0|*1) exec	sudo sudo tcpdump -ni $*;;
		*)	echo "Unknown service $f" >&2
			continue;;
	esac

	if [ "" != "${LOGS}" ]; then
		# handle multiple files CONCURRENTLY WITH -f
		echo ========== $f ==========
		vi ${NUM} ${TAIL_ARG} ${LOGS}
	else 
		if [ ! -r ${LOG} ]; then
			echo "$0: $LOG not found (by test -r)!!" >&2
			continue
		fi
		echo ========== $LOG ==========
		${TAIL_PROG} $TAIL_F $NUM $LOG
	fi

done

exit 0
