#!/bin/ksh

# watchlog - consolidate watchlog functionality.

PATH=/bin:/usr/bin:$PATH; export PATH

TAIL_PROG=tail

USAGE="$0 [-f] [-l] [-m] [-n num] [-g patt] logname"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

NUM=""
MORE=cat
LIST_ONLY=false

while getopts "fg:lmn:v" opt 
do 
 	 case "$opt" in 
		f)	TAIL_F=-f;;
		g)	PATTERN=${OPTARG};;
		l)	LIST_ONLY=true;;
		m)	MORE="more";;
		n)	NUM=-${OPTARG};;
		v)	TAIL_PROG=view;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

#if [ $# -eq 0 ]; then
#	usage
#fi

for f
do
	case $f in
		-*) ;;
		"")	echo "Usage: $0 logname" >&2; exit 1;;
		asterisk) LOG=/var/log/asterisk/messages;;
		auth)	LOG=/var/log/authlog;;
		cdr)	LOG=/var/log/asterisk/cdr-csv/Master.csv;;
		cvs|chang*) LOG=/cvs/CVSROOT/ChangeLog ;;
		cups)	LOG=/var/log/cups/error_log;;
		daem*|ppp) LOG=/var/log/daemon ;;
		ecl*) LOG=$HOME/workspace/.metadata/.log;;
		ftp)	LOG=/var/log/xferlog;;
		http|web|www) LOG=/var/www/logs/access.log ;;
		httperr|weberr) LOG=/var/www/logs/error.log ;;
		icb|hackers)	LOG=~/hacklog/`date +%Y-%m`;;
		jb7)	LOG=$HOME/jboss-as-7.1.1.Final/standalone/log/server.log;;
		jserv)	LOG=/var/www/logs/mod_jserv.log;;
		lp*)	LOG=/var/log/lpd-errs;;
		mail)	LOG=/var/log/maillog ;;
		mailman|mm) LOG=/var/spool/mailman/logs/error;;
		mess*)	LOG=/var/log/messages ;;
		nagios)	LOG=/var/log/nagios/nagios.log;;
		nohup)	LOG=${HOME}/nohup.out;;
		ob) watchlog -f cvs & watchlog -f icb & watchlog -f ports&
			exit
			;;
		openfire-errors) LOG=/usr/local/openfire/logs/error.log;;
		openfire) LOG=/usr/local/openfire/logs/all.log;;
		PF|fw)	exec tcpdump -n -e -ttt -i pflog0;;
		port*s)	LOG=~/portslog/`date +%Y-%m`;;
		ppp|chat)	LOG=/var/log/chat ;;
		radicale)	LOG=/var/log/radicale;;
		rspamd)		LOG=/var/log/rspamd/rspamd.log;;
		secure)	LOG=/var/log/secure ;;
		snort)	LOG=/var/log/snort/alert ;;
		spam) watchlog -f mail & watchlog -f daemon&
			exit
			;;
		squid)	LOG=/var/squid/logs/access.log;;
		tomcat)	exec xtail /var/tomcat/logs;;
		vnc)	LOG=~/.vnc/*.log;;
		www)	exec xtail /var/log /var/tomcat/logs;;
		wf|wildfly) LOG=${wf}/standalone/log/server.log;;
		wfa|wfaccess)	LOG=${wf}/standalone/log/access_log.log;;
		xe*)	LOG=/var/log/xenodm.log;;
		xs|xsess*|xerr*) LOG=~/.xsession-errors;;
		x|X)	LOG=/var/log/Xorg.0.log;;
		*0|*1) exec	doas doas tcpdump -ni $*;;
		*)	echo "Unknown service $f" >&2
			continue;;
	esac

	if [ "${PATTERN}" != "" ]; then
		rg -i ${PATTERN} ${LOG}
		continue
	fi

	if ${LIST_ONLY}; then
		echo $LOG
		continue
	fi

	if [ "" != "${LOGS}" ]; then
		# handle multiple files CONCURRENTLY WITH -f
		echo ========== $f ==========
		vi ${NUM} ${TAIL_ARG} ${LOGS}
	else 
		if [ ! -r ${LOG} ]; then
			echo "$0: $LOG not found (by test -r)!!" >&2
			continue
		fi
		echo ========== $LOG ==========
		${TAIL_PROG} $TAIL_F $NUM $LOG
	fi

done

exit 0
