#!/bin/sh

# watch rest of hosts on net, other than big 3

set -x

# specify daroad by ether since it chitters a lot of sap nonsense
doas tcpdump \
! host bettypc and \
! host dartagnan and \
! ether host 0:60:97:88:f1:35 \
