#!/bin/ksh

if [ "-l" == "$1" ]; then
	REDIRECT=yes
	shift
fi
HOST=${1}
INTERVAL=15

if [ "yes" == "${REDIRECT}" ]; then
	exec > /tmp/${HOST}.log
fi

while :
do
	ping -c 1 ${HOST} >/dev/null
	if [ $? -eq 0 ]; then
		echo $(date) - ${HOST} UP
	else
		echo $(date) - ${HOST} DOWN
	fi
	sleep $(( INTERVAL * 60 ))
done
