#!/bin/sh

WHITELIST=/etc/rspamd/local.d/whitelist.sender.domain.map

[ -w / ] || {
	echo "Be walking root, be talking dogs." >&2
	exit 1
}

for IP
do

	echo ${IP} >> ${WHITELIST}

	sort -u -o ${WHITELIST} ${WHITELIST}

	grep -C3 ${IP} ${WHITELIST}

done
