#!/bin/sh

# withjava - run a java program with a given java version
# when you don't want to change path/alternative/etc permanently

case `uname` in
	OpenBSD)
		case $1 in
			1.8|8)	VER=1.8.0;;
			11)		VER=11;;
			16)		VER=16;;
			17)		VER=17;;
			21)		VER=21;;
			25)		VER=25;;
			*)		echo "Unsupported ver $1"; exit 1;;
		esac
		DIR=/usr/local/jdk-$VER
		;;
	Darwin)
		DIR=$(/usr/libexec/java_home -v $1)
		case ${DIR} in
			/Library*)	;; # OK
			*)		echo "Unsupported ver $1"; exit 1;;
		esac
		;;
	*)
		echo "$0 unaware of Java on `uname`" >&2
		exit 1
		;;
esac

shift 1		# remove version

if [ ! -d "$DIR" ]; then
	echo "$0: cannot find ${DIR}"
	exit 1
fi

export JAVA_HOME=$DIR
: Prepending $JAVA_HOME/bin to PATH
export PATH=$JAVA_HOME/bin:$PATH
: Using JAVA_HOME=$DIR $* in $PWD
export JAVA_CMD=$JAVA_HOME/bin/java

unset JDK_HOME

exec $*
