#!/bin/sh

# withjava - run a java program with a given java version
# when you don't want to change path/alternative/etc permanently

case `uname` in
	OpenBSD)
		case $1 in
			1.8|8)	VER=1.8.0;;
			11)		VER=11;;
			16)		VER=16;;
			17)		VER=17;;
			21)		VER=21;;
			*)		echo "Unsupported ver $1"; exit 1;;
		esac
		DIR=/usr/local/jdk-$VER
		;;
	Darwin)
		case $1 in
			1.8|8)	VER=jdk1.8.0;;
			11)		VER=jdk-11.0.2;;
			16)		VER=temuring-16;;
			17)		VER=adoptopenjdk-17;;
			21)		VER=temurin-21;;
			22)		VER=jdk-22;;
			23)		VER=jdk-23;;
			24)		VER=jdk-24;;
			*)		echo "Unsupported ver $1"; exit 1;;
		esac
		DIR=/Library/Java/JavaVirtualMachines/$VER.jdk/Contents/Home
		;;
	*)
		echo "$0 unaware of Java on `uname`" >&2
		exit 1
		;;
esac

shift 1		# remove version

if [ ! -d "$DIR" ]; then
	echo "$0: cannot find ${DIR}"
	exit 1
fi

export JAVA_HOME=$DIR
: Prepending $JAVA_HOME/bin to PATH
export PATH=$JAVA_HOME/bin:$PATH
: Using JAVA_HOME=$DIR $* in $PWD

unset JDK_HOME

export JAVA_HOME=$DIR 

exec $*
