#!/bin/sh

# wumpus - hunt the wumpus, err, wavelan, channel.

if [ ! -w / ]; then
	echo "Run $0 as root"
	exit 1
fi

# Set session name to null to allow joining anything
wicontrol -s ""

for f in 1 2 3 4 5 6 7 8 9 10 11 12
do
	echo -n "$f "
	wicontrol -f $f
	sleep 5
	wicontrol | grep "Current netname"
done
echo ""
