#!/bin/sh

set -x

CLASSPATH=$js/target/classes
CLASSPATH=$CLASSPATH:$HOME/lib
CLASSPATH=$CLASSPATH:$HOME/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar

exec java -classpath $CLASSPATH xml.XParse $@
